### ISSUE TITLE
Something to consider: moving to an org and having more admins

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#107]
At this point in time, at least to my judgment, this package has 3 people that do [significant contributions](https://github.com/rafaqz/DimensionalData.jl/graphs/contributors?from=2019-12-26&to=2020-03-01&type=c), both in the form of PRs and of reporting issues: @rafaqz , @Datseris , @ivirshup . The entire control of the package in every possible way is under @rafaqz . I think this should not be the case, and I am opening this issue to invite  @rafaqz to consider to move this package to an org and have more people as admins here.

I already have 3 functionalities/fixes/docstuff I wanted to PR here, and because this package is central to my paid work, I know I will continue to add more features to my (local) repo naturally over time. But I am not so sure whether I should put all this work here any more, and maybe it is better to just make an add-on package in an org (probably JuliaClimate since the functions I write are useful in climate analysis anyway), where it will be much easier to have multiple admins/owners and better docs (see below). I think as a developer @rafaqz reasonably corrects and supports functionality that people add here (e.g. you have already fixed a mistake I introduced in a PR I made), but for some reason I still find it unsettling knowing that all of my work here is controlled and owned *exclusively* by another single person instead of being part of a larger collective. I don't even know whether this is moral against my employer.

The most important reason I am hesitant to continue with the current state is documentation. For me personally, the prime reason to put my work into open source is that so that other people can benefit from this. This in my eyes can only happen if (1) the repo owners care about having good documentation (2) the repo owners spend the time to do this. Unfortunately @rafaqz I am not sure how much you share this dream of mine, given my experience so far collaborating here. For example you just closed several issues asking for documentation (without this documentation actually existing yet), and also in my experience every PR here is merged without being documented. In general, my impression is also that for you documentation is a very low priority (and I think you have explicitly said so numerous times, across discussions in several different packages). 

I don't agree with this, because I am contributing here so that _everyone_ can use my contributions. Not just you and me. Because the way things work now, only you, the merger, and me, the PR author, know about the things that are added here. I am not claiming that this is bad, because this is subjective and depends on each one's priority. This package is clearly useful and good from the code perspective. But it took me a month to learn, when this could have taken a couple of days instead! This is simply not aligning with the reason I do open source nor my priorities when developing software. And if I put my (paid) work on GitHub, I want to be sure that others can use it just as well.

So what I want to suggest is that @rafaqz considers for a moment how he administers this package and consider moving to an org with more admins. Perhaps it will make this package better to have more people that can guide it to a better direction? Having it be a part of an org will likely increase contributions and usage as well.

---

At the moment I'll spend some time polishing and pushing #98 and then pushing the code for #41, but after that I think I'll wait a bit to see how things go according to the present suggestion. By the way, if I was an admin here, my focus would be documentation management, for example ensuring that no PR gets merged without documentation.

**Comment by rafaqz** [comment]
I use this for modelling and meeting real-world contracts every day and that's the main use case I built it for. It has to stay on track to meet those needs with minimal effort on my part.

At this stage no-one will be blocked from committing PRs without documentation. I often need to use features asap - like fixing near/between selection mode for interval grids. It has to work **now**, docs will come later when the interface settles. We are just not at that stage jet.

I'm not likely to give commit access to anyone in the near term. But as usual I'm happy to work with people to meet their needs as well as mine.
