### ISSUE TITLE
How to select every "singular splice" of a given dimension?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#140]
I have the situation that I need to loop over all timeseries in my data, and do a specific operation on them. For example, for 3 dimensional data Lon Lat Time I do something like
```julia
for i in 1:size(A, Lon)
    for j in 1:size(A, Lat)
        t = A[Lon(i), Lat(i)]
        # do your stuff
    end
end
```
and this loops over my timeseries, but I have to explicitly select the other dimensions. I want to generalize this so that I can use the same syntax irrespectively of what dimensions the underlying array has (provided it has a `Time` dimension)

In principle, I'd like to make a function `loop_over_timeseries` that will do this for me. It feels possible to be done from the DimensionalData.jl API, but for some reason I haven't understood yet how...

**Comment by rafaqz** [comment]
I probably need more of an example to really know what you are doing.

But I've wanted an `otherdims` method for a while, like `otherdims(A, Ti)` would give you `(Lat(), Lon())` that you could use in loops or `map` or whatever instead of writing them out. Is that what you mean?

**Comment by Datseris** [comment]
That is what I mean. I actually would also need to get the index ranges for the other dims as well, but this is done by simply doing `1:size(A, dim)`. But yes, exactly, `otherdims(A, Ti)` is exactly what I want to implement.

My guess is to get the `dims` of `A`, then do `i = findfirst` on the matching type of `Ti`, and then create a new dims tuple that doesn't have `i` ?

**Comment by rafaqz** [comment]
Yep you could make a small function to do that fairly easily. Could also do it with type comparison using recursion or `@generated` to make it type-stable.

I was thinking you could also use `eachslice`, like `(doyourstuff(slice) for slice in eachslice(A; dims=Ti()))` and broadcast over the view passed to `doyourstuff`. DD `eachslice` is a lot faster than the Base method because of type information, and might even have performance near loops in 1.5 with the new optimisations.

**Comment by Datseris** [comment]
Hm, `eachslice` doesn't do what I want. It gives me a slice _at_ the specific dimension's specific value. I want _the_ specific dimension for all other dimension's possible values. I.e. this:

```julia
for z in eachslice(X; dims = Time)
    println(size(z))
end
```
doesn't give me a timeseries (1-dimensional vector), but a full array of dimension D-1, `D = length(dims(X))`

The `otherdims` function, in combination with `1:size` is I think the thing I want. I'll post a quick implementation here soon.

**Comment by rafaqz** [comment]
Sure, I can't really tell what is meant to happen in youre example.

It's just an option where the other dims don't need to be specified, which combined with broadcast on the returned view
gives you the kind of generality you want. Just probably inside-out to how you want it.

**Comment by Datseris** [comment]
I'm having some progress, my current problem is how to get the "dimension constructor". I have
```julia
function otherdims(A, D)
    x = dims(A)
    @assert any(a -> a isa D, x)
    n = findfirst(a -> a isa D, x)
    ntuple(i -> i < n ? x[i] : x[i + 1], length(x) - 1)
end

function otherdimsiter(A, D)
    z = otherdims(A, D)
    iters = [] ...?
end
```

my plan is to do something like `lats = (Lat(i) for i in 1:size(A, Lat))` and put this inside `iters`. Problem is, I don't know how to get the constructor. Doing `typeof(z[1])` gives me 
```
Lon{Array{Float32,1},DimensionalData.Sampled{DimensionalData.Ordered{DimensionalData.Forward,DimensionalData.Forward,DimensionalData.Forward},DimensionalData.Irregular{Tuple{Nothing,Nothing}},DimensionalData.Points},Nothing}
```
how do I get just `Lon` from that?

**Comment by rafaqz** [comment]
I think what you're looking for is `DimensionalData.basetypeof`. Which works for `Dim{:x}` too, as it keeps the `:x`.

**Comment by Datseris** [comment]
Thanks a lot. So this is my current implementation, which works:
```julia

function otherdims(A, D)
    x = dims(A)
    n = dimindex(A, D)
    ntuple(i -> i < n ? x[i] : x[i + 1], length(x) - 1)
end

function alongdimidxs(A, D)
    z = otherdims(A, D)
    az = DimensionalData.basetypeof.(z)
    iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
    return Iterators.product(iters...)
end
```

I am pretty sure it is not the most performant way to do this, but feel free to use it as a starting point. At the moment I'll use this in ClimateBase

**Comment by rafaqz** [comment]
Yeah ntuple isn't type stable, probably the iterator isn't either...

I know the recursive methods in primitives.jl seem kinda weird, but that's the sacrifice for type stability with tuples of different types.

**Comment by Datseris** [comment]
@rafaqz How does #151 implement what was originally asked in this Issue? I am trying to understand how I can use `dimwise` to iterate over all remaining dimensions, but I don't see to get it.
