### ISSUE TITLE
getindex with Tuple?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#143]
Hi, 

would you accept adding a method:

```
getindex(A::AbDimArray, i::Tuple) = getindex(A, i...)
```

Which is useful (for me personally) because of iterating over some dimensions where sometimes I get iteration indices of just `Time(i)`, while some other times I get `(Time(i), Lon(j))` (notice that the latter is a tuple), because of the way `Iterators.product` works?

(p.s.: same method should exist for `view` and `setindex!`)

**Comment by Datseris** [comment]
Hm, I found a way to implement this on my end without comiting type piracy, but my code won't work with arbitrary `AbDimArray`. Feel free to close this/add this.

**Comment by rafaqz** [comment]
I normally have some method for this like:

```julia
astuple(x) = (x,)
astuple(xs::Tuple) = xs
```
Then you can splat either:

```julia
A[astuple(dims)...]
```

**Comment by Datseris** [comment]
My main reason to avoid this is to avoid the splatting happening on the user end. I've realised that it is often the case that the user has to splat, but sometimes not, e.g. in a scenario
```julia
for i in remaining_dim_idxs(A, Time)
   x = A[i...]
   B[i...] = f(x)
end
```
it is not intuitive from the user end. Also, I have to write several extra methods for functions like `remaining_dim_idxs`: a version for when the remaining dimensions are more than 1 and a version where they are exactly 1, otherwise splatting won't work because `Iterators.product` does not make a tuple for one iterator.

**Comment by rafaqz** [comment]
I think we can just let the user splat, otherwise I feel this is adding to much non base syntax.
