### ISSUE TITLE
Add aliases `DimVector`, `DimMatrix` & `DimVecOrMat`, `AbstractDimensionalVector`, `AbstractDimensionalMatrix`, `AbstractDimensionalVecOrMat`?

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#158]
Similar to `Vector`, `Matrix` & `VecOrMat`, etc. I want this feature because I want to create a type that can be used for dispatch:

```julia
const MyDimMatrix = DimArray{Int,2}

f(mat::MyDimMatrix) = sin.(mat)
```

I'm not sure if it is OK just write a `2` there. Because the type parameters of `DimArray` is rather complicated.

**Comment by rafaqz** [comment]
There is already `AbstractDimVector/AbstractDimMatrix` they just need exporting. Lets not add `AbstractDimensionalVector` etc I'm trying to move away from the longer names.

But `DimVector/DimMatrix/DimVecOrMat` for sure! I thought I had added them with `AbstractDimVector`. They should all be exported as well.

And yes it's ok to write `DimArray{Int,2}`. The first two parameters are standard `AbstractArray` parameters.

**Comment by singularitti** [comment]
I only see the [abstract ones](https://github.com/rafaqz/DimensionalData.jl/blob/10c4550ea6b9a9ce2c64cac3c5ff9f217f2fb485/src/array.jl#L18-L19). Would you mind adding it?

**Comment by rafaqz** [comment]
Yeah there's only abstract right now. Sure I can add :)

Thanks for all the fixes by the way, its great to have all those docs getting more polished.
