### ISSUE TITLE
How to make a stable iterator over slices of `otherdims`?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#165]
Related with #164 , but mostly tries to do the original goal of #140 .

I currently have this:
```julia
function otheridxs(A, D)
    z = otherdims(A, D)
    az = DimensionalData.basetypeof.(z)
    iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
    return Iterators.product(iters...)
end
```

which I use for example, if `A` has dims `(Lon, Lat, Time)` to get all timeseries of `A`:
```julia
for i in otheridxs(A, Time)
    x = A[i...] # this is a timeseries (Vector) for each lon × lat combination
end
```
or all time+latitude slices with
```julia
for i in otheridxs(A, (Time, Lat))
    x = A[i...] # matrix of time × latitude for each longitude
end
```

My current function `otheridxs` is type-unstable, even when accessed with the type-stable syntax of e.g. `otheridxs(A, (Time(), Lat())`. This of course makes sense because I make an intermediate type-unstable array `iters`.

I am looking at the source of PR #151 but I can't seem to understand how to adjust:
```julia
    map(generators) do otherdims
        I = (common..., otherdims...)
        dest[I...] .= f.(a[I...], b[common...])
    end
```

any tips?

**Comment by rafaqz** [comment]
It cant be stable in a vector... 

```julia
 iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
```

Look at `dimwise`, in utils.jl:

```julia
dimwise!(f, dest::AbstractDimArray{T,N}, a::AbstractDimArray{TA,N}, b::AbstractDimArray{TB,NB}
        ) where {T,TA,TB,N,NB} = begin
    N >= NB || error("B-array cannot have more dimensions than A array")
    comparedims(dest, a)
    common = commondims(a, dims(b))
    generators = dimwise_generators(otherdims(a, common))
    # Lazily permute B dims to match the order in A, if required
    if !dimsmatch(common, dims(b))
        b = PermutedDimsArray(b, common)
    end
    map(generators) do otherdims
        I = (common..., otherdims...)
        dest[I...] .= f.(a[I...], b[common...])
    end
    return dest
end

dimwise_generators(dims::Tuple{<:Dimension}) =  
    ((basetypeof(dims[1])(i),) for i in axes(dims[1], 1))

dimwise_generators(dims::Tuple) = begin
    dim_constructors = map(basetypeof, dims)
    Base.Generator(
        Base.Iterators.ProductIterator(map(d -> axes(d, 1), dims)),
        vals -> map(dim_constructors, vals)
    )
end
```
Its type stable:

```julia
A2 = [1 2 3; 4 5 6]
B1 = [1, 2, 3]
da2 = DimArray(A2, (X, Y))
db1 = DimArray(B1, (Y,))

julia>     dc2 = @inferred dimwise(+, da2, db1)
DimArray with dimensions:
 X: Base.OneTo(2) (NoIndex)
 Y: Base.OneTo(3) (NoIndex)
and data: 2×3 Array{Int64,2}
 2  4  6
 5  7  9
```

**Comment by rafaqz** [comment]
If you make it a full MWE I can make it stable for you

**Comment by rafaqz** [comment]
Without a MWE my guess is:

```julia
function otheridxs(A, D)
    z = otherdims(A, D)
    az = map(DimensionalData.basetypeof, z)
    iters = ((Dim(i) for i in 1:size(A, Dim)) for Dim in az)
    return Iterators.product(iters...)
end
```

That is better, although Iterators.product might not be. But there are 2 hard rules: never use vectors of dimensions,
and never `broadcast` over dimensions. Instead, `map` is your friend.

**Comment by Datseris** [comment]
Okay, I think I've found the solution as well as a MWE:
```julia
using DimensionalData
using Test
A = DimArray(rand(40, 50), (X, Y));

function otheridxs1(A, D)
    z = otherdims(A, D)
    az = map(DimensionalData.basetypeof, z)
    iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
    return Iterators.product(iters...)
end

function otheridxs2(A, D)
    z = otherdims(A, D)
    az = map(DimensionalData.basetypeof, z)
    iters = ((Dim(i) for i in 1:size(A, Dim)) for Dim in az)
    return Iterators.product(iters...)
end

function otheridxs3(A, D)
    z = otherdims(A, D)
    generators = DimensionalData.dimwise_generators(z)
    map(generators) do otherdims
        I = (otherdims...,)
    end
end


@inferred otheridxs1(A, (X(), ))
@inferred otheridxs2(A, (X(), ))
@inferred otheridxs3(A, (X(), ))

s = 0.0
for i in otheridxs3(A, (X(), ))
    a = @inferred A[i...]
    global s += sum(a)
end

@test s ≈ sum(A)

```

`otheridxs3` passes the inferrence tests. I just need to write one more version for the case of the user passing a single dimension a-la `otheridxs(A, Time())`.

**Comment by Datseris** [comment]
btw, probably this:
```julia
    map(generators) do otherdims
        I = (otherdims...,)
    end
```
is "bad" syntax, but I honestly haven't undestood what `generators` is to make it more reasonable syntax...

**Comment by rafaqz** [comment]
You don't need the splat:

```julia
otheridxs3(A, D) = map(o -> o, DimensionalData.dimwise_generators(otherdims(A, D)))
```

**Comment by Datseris** [comment]
Hm, I got happy too fast. Seems like the same function doesn't work in the real use case where the dimensions of A have value. MWE:
```julia
using DimensionalData
using Test, Dates
A = DimArray(rand(40, 50), (X, Y));

lats = -90:5:90
lons = collect(0.5:10:360)
t = Date(2000, 3, 15):Month(1):Date(2020, 3, 15)

A = zeros([length(x) for x in (lons, lats, t)]...)
d = (X(lons), Y(lats), Ti(t))

A = DimensionalArray(A, d)

otheridxs(A, D) = map(o -> o, DimensionalData.dimwise_generators(otherdims(A, D)))
otheridxs(A, X())
otheridxs(A, (X(), ) )
```
both calls to `otheridxs` error.

**Comment by rafaqz** [comment]
Ok this is another bug in `dimwise_generators`. Will fix in the same PR as the other one.

**Comment by rafaqz** [comment]
This should work now.

**Comment by Datseris** [comment]
For reference, the original method I've coded before changing my code to your `otherdims` PR was:
```julia
function otheridxs(A, D)
    z = otherdims(A, D)
    az = DimensionalData.basetypeof.(z)
    iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
    return Iterators.product(iters...)
end
```

Using my function is about 1.5 faster than the recommendation
```julia
otheridxs(A, D) = map(identity, DimensionalData.dimwise_generators(otherdims(A, D)))
```

used in loops like 
```julia
for i in otheridxs(A, Time)
            R[i] = f(view(A, i), weights(view(W, i)))
end
```

**Comment by Datseris** [comment]
`dimwise_generators` suggestion vs my version:
```

julia> @btime timeagg(mean, $A, $W);
  3.929 ms (14236 allocations: 5.76 MiB)

julia> @btime timeagg(mean, $A, $W);
  2.938 ms (10766 allocations: 5.75 MiB)
```

**Comment by rafaqz** [comment]
Please make your timings actual MWEs so I can run it too. That's the same method twice, and I don't have time to write it up myself.

And that method is not a "recommendation" I spent 5 min on it and never profiled it. It's up to you to get out the profiler and work out what is going on if you want it fast. Your top method may allow small union optimisation. The other one may not yet be fully type stable. `@code_warntype`, `ProfileView.view()` will help.

Work out _why_ one is faster than the other, that's what actually matters here.

**Comment by rafaqz** [comment]
Your first version is just returning the iterator, not actually mapping it. It you want to return just the iterator and map it later, the final version has _no runtime cost at all_.

```julia
otheridxs(A, D) = DimensionalData.dimwise_generators(otherdims(A, D))
```

**Comment by Datseris** [comment]
Mapping still has smaller performance than my original version. I.e. doing:

```julia
R .= map(i -> f(view(_A, i), weights(view(W, i))), otheridxs(A, Time()))
```

instead of my original 
```julia
for i in otheridxs(A, Time)
            R[i] = f(view(A, i), weights(view(W, i)))
end
```
gives 
```
julia> @btime timeagg(mean, $A, $W);
  3.800 ms (6746 allocations: 5.21 MiB)
```
Although the allocations have decreased a lot versus my original version:
```
julia> @btime timeagg(mean, $A, $W);
  2.932 ms (10765 allocations: 5.75 MiB)
```
my version is still faster... Why? I don't get what I am doing "wrong" (since this new version "in principle" should be faster)

**Comment by rafaqz** [comment]
Please make real MWE for your timings that I can run! I need to make that a rule for all issues. I really can't help you from what you've given.

**Comment by Datseris** [comment]
MWE
```julia
using DimensionalData, StatsBase
using Test, Dates, BenchmarkTools

lats = -90:5:90
lons = collect(0.5:10:360)
t = Date(2000, 3, 15):Month(1):Date(2020, 3, 15)

A = zeros([length(x) for x in (lons, lats, t)]...)
d = (X(lons), Y(lats), Ti(t))

A = DimensionalArray(A, d)
B = copy(A)

function otheridxs(A, D)
    z = otherdims(A, D)
    az = DimensionalData.basetypeof.(z)
    iters = [(Dim(i) for i in 1:size(A, Dim)) for Dim in az]
    return Iterators.product(iters...)
end

function f(A, B)
    map(i -> mean(view(A, i...), weights(view(B, i...))), otheridxs(A, Ti()))
end
@btime f($A, $B)

# This is the version @rafaqz suggested, but has worse performance...
otheridxs(A, D) = DimensionalData.dimwise_generators(otherdims(A, D))
@btime f($A, $B)

# use map as well
otheridxs(A, D) = map(identity, DimensionalData.dimwise_generators(otherdims(A, D)))
@btime f($A, $B)
```
```
684.799 μs (1350 allocations: 178.44 KiB)
  1.990 ms (7996 allocations: 531.19 KiB)
1.747 ms (5336 allocations: 281.72 KiB)
```

>  I really can't help you from what you've given.

I think you got confused with all the back and forth in this issue: **my method is faster than yours**, see https://github.com/rafaqz/DimensionalData.jl/issues/165#issuecomment-683447843 . Same method carries over all the way from #140 but you claimed that it is better to use the generator approach of `dimwise`. Yet the benchmarks show the opposite.

**Comment by rafaqz** [comment]
Sorry, you are confused. Your method creates a generator at runtime, mine creates a generator at compile time.

```julia
otheridxs(A, D) = DimensionalData.dimwise_generators(otherdims(A, D))
```

This has no performace overhead at all. After that it's up to you. 

Your tone is also pretty intense when I'm clearly trying to help you.

**Comment by rafaqz** [comment]
Also that's still not a MWE that makes sense to run through. You have `otheridxs` inside `f`.

Anyway, I can't help you any more, I have a few papers to finish.
