### ISSUE TITLE
`@dim` will raise an error if only import part of `DimensionalData`

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#167]
If I just write

```julia
using DimensionalData: @dim
```

The following code raises errors

```julia
julia> @dim Pressure "Pressure"
ERROR: UndefVarError: IndexMode not defined
Stacktrace:
[1] top-level scope
  @ ~/.julia/packages/DimensionalData/x0VMt/src/dimension.jl:315
```

I have to do

```julia
julia> using DimensionalData

julia> @dim Pressure "Pressure"
```

to make it work.

That means, `@dim` requires the whole package to be loaded to have effects. However, in development, this is often not the case. Should the [`dimmacro`](https://github.com/rafaqz/DimensionalData.jl/blob/5786c8db1136851848a82bf02ea0011c61b9a2c7/src/dimension.jl#L313-L326) be modified?

**Comment by rafaqz** [comment]
Sure where I use `@dim` I'm always `using` the whole package. But you could just add `DimensionalData` where required in the macro, something like:

```julia
dimmacro(typ, supertype, name=string(typ), shortname=string(typ)) =
    esc(quote
        Base.@__doc__ struct $typ{T,IM<:DimensionalData.IndexMode,M} <: $supertype{T,IM,M}
            val::T
            mode::IM
            metadata::M
        end
        $typ(val=:; mode=DimensionalData.AutoMode(), metadata=nothing) =
            $typ(val, mode, metadata)
        $typ(val, mode, metadata=nothing) =
            $typ(val, mode, metadata)
        DimensionalData.name(::Type{<:$typ}) = $name
        DimensionalData.shortname(::Type{<:$typ}) = $shortname
    end)
end
```

And make a PR

**Comment by rafaqz** [comment]
By the way, you can also choose a supertype and plotting axis for pressure:

```julia
@dim Pressure ZDim
```

You also don't need the "Pressure" part as its the same as the type, and thats the default. I probably need to update the docs on this.
