### ISSUE TITLE
Is there a way to set a dim to a different type?

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#170]
The current `setdims` seems only support set dims to the same type. But sometimes I do want to set a dim to another type. For example, change `Volume` to `Pressure` but they label the same `data` of the `DimArray` because `Pressure` can be calculated from `Volume`. Is it possible to use a syntax like

```julia
A = DimArray(ones(10, 10), (X, Y(10:10:100)))
setdims(A, X => Z(1:10))
```

which requires `Z` has the same size as `X`?

**Comment by rafaqz** [comment]
`swapdims` does that. https://github.com/rafaqz/DimensionalData.jl/blob/master/src/primitives.jl#L406

But it's a little low-level.

Your syntax suggestion looks good! I'm working on `set` being the method that sets everything, maybe we can use that syntax for swapping dims in `set`. I will eventually not export `setdims` or `swapdims`

**Comment by rafaqz** [comment]
Also remember you can change anything using `rebuild` which is what happens underneath anyway. I's just a bit cumbersome to use.

**Comment by singularitti** [comment]
> `swapdims` does that. https://github.com/rafaqz/DimensionalData.jl/blob/master/src/primitives.jl#L406

I get it. I overlooked this method because I thought it "swaps" existing dimensions, like a permutation, not with a new one.

I got the inspiration from [`replace`](http://docs.julialang.org/en/v1/base/collections/#Base.replace-Tuple%7BAny,Vararg%7BPair,N%7D%20where%20N%7D), I was a little bit worried at the beginning because I think the objects on the 2 sides of `=>` are a type and an instance. But then I found that `DimArray` does allow same axes:

```julia
DimArray with dimensions:
 Z: 2:2:20 (Sampled: Ordered Regular Points)
 Z: 2:2:20 (Sampled: Ordered Regular Points)
and data: 10×10 Array{Float64,2}
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
```

Then I think it is fine because `setdims(A, z => x)` can be necessary. A better syntax like `set` is appreciated, also.

**Comment by rafaqz** [comment]
`replace` is a good precedent that I hadn't though of before this issue. I will build it into `set` for everything. The nice thing about `=>` is you can have anything on both sides. We can do  `set(A, :a => Categorical(), X => Sampled())` and mix symbol and type syntax in the one call (:a is shorthand for `Dim{:a}`).

And yes you can have multiples of the same dim. Everything works as expected too - like `dims(A, (Z, Z)` will give you both, not the first one twice as would happen naively. For a permutation you can use `sordims` or `Base.permutedims`. 

But these are all just methods/names I've made up in the last year or so, and all open to improvements. How to work with highly typed immutable objects like `Dimension` isn't that deeply explored yet in julia, so there is probably a lot of simplification and improvement that can happen.

**Comment by singularitti** [comment]
One thing that `swapdims` cannot satisfy my needs: As far as I understand (correct me if I'm wrong), `swapdims` requires you explicitly write **all** `newdims` in the order you want, it cannot pick out the one you don't want and replace it with a new one.

For example, `A = DimArray(ones(2, 3, 4), (X, Y, Z))`, now I want to replace the `Z` axis with `Y(2:2:8)`, I have to explicitly write

```julia
julia> swapdims(A, (X, Y, Y(2:2:8)));

julia> function f(::DimArray{T,3}) where {T}
    # do something
    swapdims(A, (X, Y, Y(2:2:8)))
end
```

But, sometimes the order of the dimensions don't matter, so `A` can be a `DimArray` with `Z, Y, X`, `X, Z, Y`, ..., all 6 permutations. I can't write 6 methods for just swapping an axis in function `f`, this is no Julian. For `Array`s with more dimensions, this is simply impossible. Is there a workaround to do this now?

**Comment by rafaqz** [comment]
Yeah `set` deals with this. Check the PR. There are a few things to sort before it is in and I'm pretty busy right now so it might be a while.

For now you can combine `sortdims` and `swapdims`. Sortdims takes any dimensions and sorts them in the order of some other dimension tuple, filling the gaps with `nothing`. `swapdims` ignores nothing, so it should just work.

Again they are too low-level for user and `set` will replace them, but for now you should get something working with that.

**Comment by rafaqz** [comment]
Set is now merged. This should work:
```julia
set(A, X = Z(1:10))
```
