### ISSUE TITLE
Should `A` in `abstract type AbstractDimArray{T,N,D<:Tuple,A} <: AbstractArray{T,N} end` be constrained?

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#174]
I wonder whether the `A` parameter is necessary here. Could it be

```julia
abstract type AbstractDimArray{T,N,D<:Tuple,A<:AbstractArray{T,N}} <: AbstractArray{T,N} end
```

therefore

```julia
julia> const AbstractDimVector = AbstractDimArray{T,1} where T
AbstractDimArray{T,1,D,A} where A<:AbstractArray{T,1} where D<:Tuple where T

julia> const AbstractDimMatrix = AbstractDimArray{T,2} where T
AbstractDimArray{T,2,D,A} where A<:AbstractArray{T,2} where D<:Tuple where T
```

kind of reduce the possibilities. I am trying to define an `AbstractDimMatrix` by my own, so I don't know how specific I should be. I was writing

```julia
const Wavevector = Dim{:Wavevector}
const Branch = Dim{:Branch}
const FreqAxes = Union{Tuple{Wavevector,Branch},Tuple{Branch,Wavevector}}
const Freq = AbstractDimMatrix{
    T,
    <:FreqAxes,
    <:AbstractMatrix{T},
} where {T<:Union{Frequency,Energy,Wavenumber}}
```

Is it good?

**Comment by singularitti** [comment]
This issue is kind of related to #158, where the question also raised when I was writing this code.

**Comment by singularitti** [comment]
I actually change that, and every test passes.

**Comment by rafaqz** [comment]
Your right, the `A` param prob isn't needed. It's a breaking change for dependent packages like GeoData.jl, but there are a _lot_ of breaking changes coming up, so if you wanna make a PR. Also #158 is surprisingly hard to do well. Have a go if you like.

**Comment by rafaqz** [comment]
```julia
const Wavevector = Dim{:Wavevector}
const Branch = Dim{:Branch}
const FreqAxes = Union{Tuple{Wavevector,Branch},Tuple{Branch,Wavevector}}
const Freq = AbstractDimMatrix{
    T,
    <:FreqAxes,
    <:AbstractMatrix{T},
} where {T<:Union{Frequency,Energy,Wavenumber}}
```

I'm not really sure what you are trying to do here - what is the advantage of having the type `Freq`?

**Comment by singularitti** [comment]
> I'm not really sure what you are trying to do here - what is the advantage of having the type `Freq`?

Oh, I want to dispatch on this type: an `AbstractDimMatrix` with specific axes.

**Comment by rafaqz** [comment]
Oh right. You can also do it with traits i you own the methods:

```julia
dimtrait(A) = all(hasdim(A, (Branch(), Wavevector())) ? Freq() : NoFreq()
somemethod(A) = somemethod(dimtrait(A), A)
somemethod(::Freq, A) = ...
```

**Comment by rafaqz** [comment]
For the dims you could also do:

```julia
@dim Wavevector XDim
@dim Branch YDim
```

If you want to control how they are plotted

**Comment by rafaqz** [comment]
So as usual there was a reason I just forgot what it was:

https://github.com/rafaqz/DimensionalData.jl/blob/master/src/broadcast.jl#L26-L29

`BroadcastStyle` needs the parent array type to be a type paremeter. `A` is actually necessary.
