### ISSUE TITLE
Should `reverse` also reverse the dimension?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#190]
Hi there,

I have some new climate data, which have input latitude reverse, i.e. it starts from 90 and goes to -90 in descending order. This sometimes makes plotting weird, but anyways this doesn't matter.

I can `reverse` the array, but this does not reverse the actual dimension, so that even though the data of A are reverse along the latitude, the latitude dimension stays as is. 

Should there be a method that reverses both the array and the underlying dimension that is chosen? Perhaps a function with different name than `reverse`?

**Comment by rafaqz** [comment]
Yeah It's kind of arbitrary what we do with that - everything still works with the index whichever way so it's not entirely necessary - sometimes it starts out with a reverse relationship anyway.

But there are a bunch of `reverse` methods and `reorder` to do these things. But it looks like the new `reverse` methods didn't get documented in the last overhaul (predictably...). But you can do `reverse(IndexOrder, a)`, and `reverse(a)` just calls `reverse(ArrayOrder, a)` anyway. 

https://github.com/rafaqz/DimensionalData.jl/blob/master/src/utils.jl

`reorder` is also good to force a certain order, instead of reversing the exising order.

Anyway, I'll document the new methods for `reverse`.

**Comment by Datseris** [comment]
To clarify: `reverse(IndexOrder, a; dim = Lat)` would reverse both the array data `a` and the underlying dimension?

**Comment by rafaqz** [comment]
No sorry that will just reverse the index if you need to do that.  

But for clarity: when you `reverse(a)` (the `ArrayOrder`) the `Relation` will be reverse as well - so it's tracked that the relationship between the array and the index is now flipped - and everything should still work fine like that. 

If not it's a bug.

**Comment by rafaqz** [comment]
I'm not sure if I can cope with having another reverse method (there are already too many!), see how you go just calling both of those things. It's possible that what you want is in fact a better default behaviour, and we could instead just change what reverse does.

**Comment by Datseris** [comment]
Unfortunately it only became more confusing for me... :( 

Let's say I have `A` with only one dimension, latitude, that has values `90:-1:-90`. Let's also say that `A` has the value 0 at latitude 90 and the value 1 at latitude -90.

When I do `A[At(Lat(90)]` I get the value 0. Then I have `B = reverse(A; dim = Lat)`. What should we expect `B[At(Lat(90))]` to yield? I would imagine that it would yield the value 1. Is this the case? This would make intuitive sense for me, based on how `reverse` works on standard arrays in Julia base.

The scenario I'm looking for is different: I want to create a `C = some_reverse_arguments(A)`, so that now `dims(C, Lat).val` is the range `-90:90` _and_ the values of the underlying array of `C` have been reversed, as per the standard application of `Base.reverse(A.data)`. Then, when I do `C[At(Lat(90))]` I thus again obtain the value 0. 

Does this make sense?

**Comment by rafaqz** [comment]
>What should we expect B[At(Lat(90))] to yield? I would imagine that it would yield the value 1. Is this the case? This would make intuitive sense for me, based on how reverse works on standard arrays in Julia base.

It should always return 1 or it's a bug.  But currently it works like that without flipping the actual index - it just flips the `Relation`.

>The scenario I'm looking for is different: I want to create a C = some_reverse_arguments(A), so that now dims(C, Lat).val is the range -90:90 and the values of the underlying array of C have been reversed, as per the standard application of Base.reverse(A.data). Then, when I do C[At(Lat(90))] I thus again obtain the value 0.
 
What you want is as things currently stand is (using the most verbose form for clarity):
```julia
reverse(IndexOrder, reverse(ArrayOrder, a))
```

But probably what you want should be the default. ie.

```julia
Base.reverse(A::AbstractDimArray; dims=1) = reverse(IndexOrder, reverse(ArrayOrder, A, dims), dims)
```

Currently the code is.
```julia
Base.reverse(A::AbstractDimArray; dims=1) = reverse(ArrayOrder, A, dims)
```

So the answer to the question you pose is in the title is: *yes*, it probably should, as it's what people will expect - it doesn't matter that indexing works either way, it's a better mental model if both are reversed together.


BTW. The reason these things are decoupled is for dealing with the case where the index is meant to be a reverse sequence. We need to know that it's backwards so `searchsortedfirst` still works, but we also need to know not to plot the array backwards to match it. So there is the `ArrayOrder,Indexorder,Relation` traits to track that.

But its too complicated. I know - it needs some thought.

**Comment by Datseris** [comment]
I agree with the new default, I think it is the most reasonable thing to expect.

**Comment by rafaqz** [comment]
It just takes 5% longer to run ;) But I'll swap it over when I have some time.
