### ISSUE TITLE
Indexing along non-existent dimensions should produce a warning

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#196]
I was surprised to find that I can index into a `DimArray` along the `Ti` and `Z` dimensions even when the `DimArray` only had `X` and `Y` dimensions (and use invalid indices like `-Inf` and strings).

# Minimal working example

```julia
julia> using DimensionalData

julia> A = DimArray(randn(3, 3), (X, Y))
DimArray with dimensions:
 X (type X): Base.OneTo(3) (NoIndex)
 Y (type Y): Base.OneTo(3) (NoIndex)
and data: 3×3 Array{Float64,2}
 2.47519   -0.425256   0.766621
 0.966197  -0.803147  -0.822271
 1.08084    2.11151    0.285326

julia> A[Ti(1:2)]  # I expect an error, e.g. ArgumentError exception
DimArray with dimensions:
 X (type X): Base.OneTo(3) (NoIndex)
 Y (type Y): Base.OneTo(3) (NoIndex)
and data: 3×3 Array{Float64,2}
 2.47519   -0.425256   0.766621
 0.966197  -0.803147  -0.822271
 1.08084    2.11151    0.285326

julia> A[Z=-Inf]  # Also expecting an error
DimArray with dimensions:
 X (type X): Base.OneTo(3) (NoIndex)
 Y (type Y): Base.OneTo(3) (NoIndex)
and data: 3×3 Array{Float64,2}
 2.47519   -0.425256   0.766621
 0.966197  -0.803147  -0.822271
 1.08084    2.11151    0.285326

julia> A[Z="one million"]  # Definitely expecting an error haha
DimArray with dimensions:
 X (type X): Base.OneTo(3) (NoIndex)
 Y (type Y): Base.OneTo(3) (NoIndex)
and data: 3×3 Array{Float64,2}
 2.47519   -0.425256   0.766621
 0.966197  -0.803147  -0.822271
 1.08084    2.11151    0.285326

```

# Julia environment

```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, cascadelake)

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [c7e460c6] ArgParse v1.1.0
  [fbb218c0] BSON v0.2.6
  [6e4b80f9] BenchmarkTools v0.5.0
  [052768ef] CUDA v1.3.3
  [8f4d0f93] Conda v1.4.1
  [d58978e5] Dagger v0.9.2
  [68e73e28] DaggerGPU v0.1.1 `https://github.com/jpsamaroo/DaggerGPU.jl.git#master`
  [933edf66] DarkMode v0.1.0 `https://github.com/Pocket-titan/DarkMode#master`
  [a93c6f00] DataFrames v0.21.8
  [0703355e] DimensionalData v0.13.3
  [9b6fcbb8] GeoData v0.2.1 `https://github.com/rafaqz/GeoData.jl.git#master`
  [7073ff75] IJulia v1.21.4
  [85f8d34a] NCDatasets v0.10.4
  [9e8cae18] Oceananigans v0.43.0
  [c3e4b0f8] Pluto v0.12.4
  [08abe8d2] PrettyTables v0.9.1 `https://github.com/ronisbr/PrettyTables.jl.git#master`
  [438e738f] PyCall v1.92.1
  [d330b81b] PyPlot v2.9.0
  [295af30f] Revise v3.1.3
  [a759f4b9] TimerOutputs v0.5.6
```

**Comment by rafaqz** [comment]
Yep I've swung both ways on that. It could maybe be a warning?

But it's actually kind of useful in some contexts. For instance tiff files have band dimensions, but by far the most common is `Band(1)`, but you need to standardise and always have a `Band` dim. To get a standard 2 dimensional array with the same code for a netcdf file you can just do:

```julia
A[Band(1)] 
```

And it will work for either - removing the band dim if it's there, doing nothing if it isn't. That kind of cross format standardised scripting is important in a lot of the work I use this package for.

**Comment by ali-ramadhan** [comment]
I see, that makes sense. I think adding a warning would be a very good idea.

I guess what scared me was that I could end up incorrectly indexing along a non-existent dimension deep in a script and then scratch my head for hours wondering why my script is producing the wrong answer, when a predictable error or a warning could have saved me hours of grief.

**Comment by rafaqz** [comment]
Yes I see your point. Lets make it a warning.

**Comment by rafaqz** [comment]
By the way the invalid indexes aren't really an issue - the whole unmatched Dimension is removed based on it's wrapper type not matching, without it's contents ever being checked.

**Comment by ali-ramadhan** [comment]
I see, you're right. You can't index with `-Inf` or `"one million"` into an existing dimension so indeed it would probably never be an issue.

**Comment by Datseris** [comment]
I agree with the warning, seems like the best of both worlds.
