### ISSUE TITLE
Bring back forcing the use of At() in selectors - the current syntax is too ambiguous.

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#197]
~~This is what AxisKeys.jl does, and it's better.~~

```julia
A(X(2), Y(Near(5)))
```

~~Array indexing is cleanly separated from dimensional indexing. This will allow things like circular geometry using negative value Int to work where it should throw an error.~~

~~There will need to be a long depreciation period with the current syntax.~~

No. Use `At()` instead.

**Comment by rafaqz** [comment]
But also this syntax is kind of weird. Not having get/set with the same syntax is a downside.

**Comment by Datseris** [comment]
Why is `A(X(2), Y(Near(5)))` better than `A[X(2), Y(Near(5))]`, or, better question, what's the difference functionally? In both cases you overload a function. This is either `getindex` or `(a::AbstarctDimArray)`

**Comment by rafaqz** [comment]
One reason is: what does `A[x=1]` do compared to `A[x=1.0]`?

Using the other syntax separates those things completely. Maybe I should just bring back forcing you to use `A[x=At(1.0)]` so you clearly are using a selector. It's just a bit verbose.

**Comment by Datseris** [comment]
Oh, I didn't know `A[x=1]` was even an option :D 

I don't like this I must say. Only one syntax should exist. For me, so far, it was perfectly clear, because `A[Dim(whatever)]` was always index accessing, while `A[Dim(Accessor(whatever))]` was always value accessing.

Seems more like stylistic choice than anything to be honest, but my take is that only one way to do the thing should exist. either `()` versus `[]`, or selectors vs no selectors. I prefer selectors because it is clear whether we use `At` or `Near`. This is critical. With `x = 1.0` I assume it uses at, but it could be near as well, who knows!

**Comment by rafaqz** [comment]
Yeah I'm kind of with you on that. But a lot of people seem to like the terse syntax. I think it's pretty clearly `At` due to the equality sign, but maybe forcing use of `At()` is better. And it's a very short word - I chose it 100% to make this limitation more tolerable. 

But using `=` is nice - I get tired of all the brackets, and it means the `Dim{:x}` dims are actually usable. It's slightly ambiguous in that types `X` "win" over `Dim{:X}` but I don't wee that being a problem in practise, it would be pretty weird to have both anyway.

**Comment by Datseris** [comment]
That's fine for, I think you're suggesting the syntaxes:

```
A[1:5, 2] # standard
A[Time = 1:5, Lat = 2] # dimensional, but with indexes
A(Time = At(1.5), Lat = Between(1, 20)] # dimensional, but with values
```
that is fine with me.

**Comment by Datseris** [comment]
Although I have to say, provided that `At` is requested explicitly, I'd much rather have 
```
A[Time = At(1.5), Lat = Between(1, 20)] # dimensional, but with values
```
instead of 
```
A(Time = At(1.5), Lat = Between(1, 20)) # dimensional, but with values
```

**Comment by rafaqz** [comment]
Yeah absolutely At would be instead of the curved braces! `At` also deals with `setindex!` which is much nicer.

**Comment by rafaqz** [comment]
There are some other problem thought too, like `end` being buggy inside `[]`. You just can't use in it `()`

**Comment by Datseris** [comment]
If selectors are explicitly demanded, then I think you can achieve all 3 syntaxes with only using `[ ]` and never `( )` which I definitely prefer. It is well known that in Julia accessing arrays is done with `[ ]`. The syntax `A( ... )` feels out of place, at least to me.

**Comment by rafaqz** [comment]
Yeah. Thats why I made the second comment. Logically it kind of make sense, but its just weird in practice

**Comment by rafaqz** [comment]
But, thinking about it more, this syntax is great to have:

```julia
da = DimArray(rand(4), X(Val((:a, :b, :c, :d))))
da[X=:c] 
da[:d]
```

I use it in some models where writing `At(:b)` everywhere would be really verbose. And using a symbol like this isn't really ambiguous. 

To me the real problem is `Int` and vector/range of `Int` - and that it is a totally different thing to float or vector/range of float.

**Comment by Datseris** [comment]
I'm still in favor for the minimalist design and minimizing source code. Doing `X = At(:b)` is not that much more verbose, however trying to make special exceptions so that `X = value` is allowed for all value types besides `value::Int` might be complicated. I think you know best how easy it is to allow `X = value` unless value is `::Int`.

**Comment by Datseris** [comment]
Actually, no, I don't agree with allowing `X =value`. For the reason that a user might want to use their own custom array versions with dimensional data. In principle any subtype of `AbstractArray` should be valid. And users might extend the traditional getindex with anyway they want. So for them the syntax `X = whatever` can be always be thought of direct translation to `getindex`, and thus they could use their custom indexing for their custom types nevertheless, while still having the benefit of indexing by value using `x = At(whatever)`.

**Comment by rafaqz** [comment]
`X = value unless value is ::Int.`

This is the current behaviour already, roughly. 

What you say about user extension is a key reason to just limit it to `Symbol` instead of the current behaviour where everything is `At()` except `Int/AbstractArray{Int}`. But `Symbol` is pretty useful for categorical things. Anyway I'll sit on this a while, and get a release out in the meantime.
