### ISSUE TITLE
Array interfaces for dims?

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#2]
`AbstractDimension` could be `<: AbstractArray` (`AbstractArray{T,N}`, not just `Vector`). This gets a little weird when they hold `Number`.

They could also just define a bunch of array methods without being `<: AbstractArray`

it would mostly just reduce the use of `val()` but probably has other benefits

**Comment by Datseris** [comment]
Shouldn't they be `<: AbstractVector` instead of `AbstractArray`?

**Comment by rafaqz** [comment]
They can be multi-dimensional arrays in some kinds of convoluted spatial grids.

**Comment by rafaqz** [comment]
Dimesion can't be `<: AbastractArray` because they also do other things. But we can do some things manually as they are needed.
