### ISSUE TITLE
Would be nice if dimensions printed their length

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#206]
For example, when printing a `GeoArray` it would be nice to be able to see the length of each dimension. Also happy to implement this although I couldn't find out exactly what to change in `prettyprint.jl`.

From:

```julia
julia> ds[:speed]
GeoArray (named speed) with dimensions:
 x (type xF): Float64[-200000.0, -193750.0, …, 193750.0, 200000.0] (Sampled: Ordered Regular Intervals)
 y (type yC): Float64[-295312.5, -285937.5, …, 285937.5, 295312.5] (Sampled: Ordered Regular Intervals)
 z (type zC): Float64[-984.375, -953.125, …, -46.875, -15.625] (Sampled: Ordered Regular Intervals)
 Time (type Ti): Float64[0.0, 173149.89134132874, …, 3.1276824357994184e7, 3.1450398298932295e7] (Sampled: Ordered Irregular Intervals)
```

Proposed change:

```julia
julia> ds[:speed]
GeoArray (named speed) with dimensions:
 x (type xF): Float64[-200000.0, -193750.0, …, 193750.0, 200000.0] (Sampled: 65 Ordered Regular Intervals)
 y (type yC): Float64[-295312.5, -285937.5, …, 285937.5, 295312.5] (Sampled: 64 Ordered Regular Intervals)
 z (type zC): Float64[-984.375, -953.125, …, -46.875, -15.625] (Sampled: 32 Ordered Regular Intervals)
 Time (type Ti): Float64[0.0, 173149.89134132874, …, 3.1276824357994184e7, 3.1450398298932295e7] (Sampled: 183 Ordered Irregular Intervals)
```

**Comment by rafaqz** [comment]
Good idea. It used to print that information below with the array. But lets get it standardised with `GeoStack` printing and print the size with the dim.

Thanks for all the help and PRs by the way, this kind of polishing is really what the package needs.

**Comment by ali-ramadhan** [comment]
No problem! Hoping to use these packages more so glad I can help!

Is this a DimensionalData.jl issue or a GeoData.jl issue? Seems like printing `(Sampled: Ordered Regular Intervals)` is in this repo.

Wasn't able to find the right lines to change but if you give me a hint I'm happy to open a PR.

**Comment by rafaqz** [comment]
https://github.com/rafaqz/DimensionalData.jl/blob/master/src/show.jl#L30-L62

**Comment by ali-ramadhan** [comment]
Thanks! Spent too long looking for where "Sampled" and "Irregular" were being printed haha.
