### ISSUE TITLE
docstring for `sel2indices` and extending it

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#207]
Hi there,

can you please add a documentation string to `sel2indices`? I know it is internal but now I need to extend it and I am not sure exactly what the input types and output type should be.

In principle I have a context specific dimension `Coord` that represents two dimensional points. I want to implement an indexing behavor for `Coord` that satisfies:
```
A[Coord(Lat(Between(-90, 0))]
```
so that this selects all points whose latitude is between `-90` and `0` (examples).

Can you provide some help on where to get started? I'm really not sure which method of `sel2indices` I should attempt to extend.

**Comment by rafaqz** [comment]
I'm guessing you want it to compose too:

```julia
A[Coord(Lat(Between(-90, 0)), Ti(At(DateTime(2002, 1, 3))]
```

So in the end in this case would return `Tuple{Vector{Bool}, Int}` to index into the main array.

There are  bunch of comments in the file, but I don't really have time to document unexported internal methods. Instead, I can get you started, but you will probably have to read the code in selectors.jl `sel2indices` methods and follow how it works to be able to do something like this. 

The difference with current behaviour is the `Coord` wrapper. You will need to use `dims2indices` again inside it to get the internal `Lat` index.  Another difference is the fact that the coordinates are not sorted - so you will need to generate a vector of `Bool` to index an interval `Between` two points - but that should work fine.

To use the existing selectors as much as possible, the `Coord` index should be matrix with length of the array axis and width of the number of dims in the `Coord`. Lat/Lon etc can specify which column of the matrix is used in `sel2indices`. You will need a `dims` tuple field on the `Coord` dim, and will have to run`dims2indices` on it to get the index for `Lat` in your example. Then you can use it to `view` into the index to get a vector you can use in `sel2indices`.

You will need to use `Unordered` mode. 
- `At` and `Where` will work as-is
- `Between` usually uses `searchsortedfirst` which is ordered. But you can just use `Where` instead - as you actually have to search every value, which is what `Where` does. `Where(x -> x >= lower, < upper)` should do the trick, where `lower` and `upper` are the lowest and highest value in the tuple that `Between` holds. 

- `Near` is possible but harder. You would have to actually write that specifically from scratch. It could minimise the difference between the selected point and the values in the index. 

If you want to index with both `Lat` and `Lon` using `Between`, just use do both separately and use `A .&= B` on the bool vectors to get the union.

**Comment by Datseris** [comment]
Hm, at the moment what you describe is too advanced for what I want to do, so I'll postpone it for now. I don't need the `dims` field and everything else, as I know the order of dimensions within `Coord`. I also don't need to do the matrix thing and propagate everything, coordinates are stored efficiently as vector of static vectors.

After all, I only want to get `A[Coord(Lat(Between(x, y)))]` working. That's all for now, I don't want to make a full user API.

I went through the source and use `@which` to see which functions propagate to which. Then, I concluded that this is the method I really have to extend:

```julia
function DimensionalData.dims2indices(c::Coord, sel::Lat{Between})
    lats, idxs = uniquelats(c.val)
    l1, l2 = sel.val.val
    # Notice that lats is guaranteed sorted for gaussian equal area
    i1 = searchsortedfirst(lats, l1)
    i2 = searchsortedlast(lats, l2)
    return idxs[i1][1]:idxs[i2][end]
end
```
Don't worry about `uniquelats` for now, just some internal function. The problem is that when I run this method via e.g. `A[Coord(Lat(Between(-90, -80)))]` I get

```
ERROR: ArgumentError: Latitude (type Lat): Between{Tuple{Int64,Int64}}((-90, -80)) (AutoMode)
not found in Spatial Coordinates (type Coord): StaticArrays.SArray{Tuple{2},Float32,1,2}[Float32[0.0, -88.288376], Float32[60.0, -88.288376], …, Float32[240.0, 88.288376], Float32[300.0, 88.288376]] (Sampled: Unordered Irregular Points)
Stacktrace:
 [1] selvalnotfound(::Coord{Array{StaticArrays.SArray{Tuple{2},Float32,1,2},1},DimensionalData.Sampled{DimensionalData.Unordered{DimensionalData.ForwardRelation},DimensionalData.Irregular{Tuple{Nothing,Nothing}},DimensionalData.Points},Dict{String,String}}, ::Lat{Between{Tuple{Int64,Int64}},DimensionalData.AutoMode{DimensionalData.AutoOrder},Nothing}) at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:322
 [2] at at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:318 [inlined]
```

So I was wrong, apparently I need to extend something else. Can you provide some direction here?

**Comment by rafaqz** [comment]
Ok I thought you wanted to contribute a general method for DimensionalData.jl.

Please read the code for `dims2indices`, all those methods have a third argument.

**Comment by Datseris** [comment]
```
dims2indices(dim::Dimension, lookup, emptyval=Colon())
```
defines two methods. A 2-argument one and a 3-argument one. Adding `, emptyval = Colon()` to the function I've cited above changes nothing... I get exactly the same error.

**Comment by rafaqz** [comment]
Your also dispatching on the pre-sorted phase of `dims2indices` - what is actually passed to `dims2indices` from `getindex` is a tuple of dimensions. This has to be sorted. After that it is passed to the even-more-internal method:

```julia
_dims2indices(dim::Dimension, lookup, emptyval)
```

**Comment by Datseris** [comment]
To be clear here, is `lookup` the argument given to the dimension? E.g. when I do `A[Lat(5)]`, `lookup = 5`? This is what I've understood so far from the source.

**Comment by rafaqz** [comment]
Dim and lookup are both dimensions! Otherwise dims2indices isn't even called. I should have picked that up in you code, I'm a little rusty on this too.

`dim` is the `Dimension` holding the index, `lookup` is the `Dimension` holding the `Selector/Int/Range` etc. at this point, they have been matched by `dims2indices` in the generated function to be of the same type. You just have to work out what to do with them. 


```julia
 A Dimension type always means Colon(), as if it was constructed with the default value.
@inline _dims2indices(dim::Dimension, lookup::Type{<:Dimension}, emptyval) = Colon()
# Nothing means nothing was passed for this dimension, return the emptyval
@inline _dims2indices(dim::Dimension, lookup::Nothing, emptyval) = emptyval
# Simply unwrap dimensions
@inline _dims2indices(dim::Dimension, lookup::Dimension, emptyval) = val(lookup)
# Pass `Selector`s to sel2indices
@inline _dims2indices(dim::Dimension, lookup::Dimension{<:Selector}, emptyval) =
    sel2indices(dim, val(lookup))
```
If the Dimension holds a selector we pass it to `sel2indices` from here. Otherwise we just return an index to go to the parent array.

**Comment by rafaqz** [comment]
```julia
@inline _dims2indices(dim::Dimension, lookup::Type{<:Coord}, emptyval) = do your things
```

**Comment by rafaqz** [comment]
You could also just define `sel2indices` instead, as that will be called anyway - using your original method signature for `dims2indices`

**Comment by rafaqz** [comment]
```julia
function DimensionalData.sel2indices(c::Coord, sel::Lat{Between})
    lats, idxs = uniquelats(c.val)
    l1, l2 = sel.val.val
    # Notice that lats is guaranteed sorted for gaussian equal area
    i1 = searchsortedfirst(lats, l1)
    i2 = searchsortedlast(lats, l2)
    return idxs[i1][1]:idxs[i2][end]
end
```

**Comment by Datseris** [comment]
Alright, here is what I have now:

First of all, `Coord` is a standard dimension, nothing fancy. For reproducibility:
```julia
using DimensionalData
@dim Lat IndependentDim "Latitude"
@dim Coord IndependentDim "Spatial Coordinates"
A = DimensionalArray(rand(4, 4), (Coord(1:4), Ti(1:4)))

```

I've extended the following two methods:

```julia
function DimensionalData._dims2indices(c::Coord, sel::Coord{Lat{Between}}, emptyval = Colon())
    l1, l2 = sel.val.val
    return l1:l2 # just for testing
end

function DimensionalData.sel2indices(c::Coord, sel::Lat{Between}, emptyval = Colon())
    l1, l2 = sel.val.val
    return l1:l2 # just for testing
end
```

And I do:
```julia
A[Coord(1:2)] #  works 
A[Coord(Lat(Between(1, 2))] # errors
```

```
ERROR: ArgumentError: Latitude (type Lat): Between{Tuple{Int64,Int64}}((1, 2)) (AutoMode) not
found in Spatial Coordinates (type Coord): 1:4 (Sampled: Ordered Regular Points)
Stacktrace:
 [1] selvalnotfound(::Coord{UnitRange{Int64},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Int64},Points},Nothing}, ::Lat{Between{Tuple{Int64,Int64}},AutoMode{AutoOrder},Nothing}) at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:322
 [2] at at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:318 [inlined]
 [3] at at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:304 [inlined]
 [4] sel2indices at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:255 [inlined]
 [5] sel2indices at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:249 [inlined]
 [6] sel2indices at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:214 [inlined]
 [7] #156 at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:204 [inlined]
 [8] map at .\tuple.jl:177 [inlined]
 [9] sel2indices at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:203 [inlined]
 [10] sel2indices at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\selector.jl:201 [inlined]
 [11] getindex at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\array.jl:142 [inlined]
 [12] getindex(::DimArray{Float64,2,Tuple{Coord{UnitRange{Int64},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Int64},Points},Nothing},DimensionalData.Ti{UnitRange{Int64},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Int64},Points},Nothing}},Tuple{},Array{Float64,2},Symbol,Nothing}, ::Coord{Lat{Between{Tuple{Int64,Int64}},AutoMode{AutoOrder},Nothing},AutoMode{AutoOrder},Nothing}) at C:\Users\m300808\.julia\packages\DimensionalData\OJqhV\src\array.jl:127
```

It always tries to find `Lat` inside `Coord` for some reason. Should I be defining `Coord` differently, not as a standard dimension?

**Comment by Datseris** [comment]
Notice that doing this:
```julia
function DimensionalData._dims2indices(c::Coord, sel::Coord{Lat{Between}}, emptyval = Colon())
    l1, l2 = sel.val.val
    return coord_latitudes_between(c, l1, l2) # this is Vector{Int}
end
```
works fine (in my real code I actually do correctly select specific latitudes, but now without writing `Lat(Between)`, but only `Between()`, i.e. I'm overwriting the existing functionality of `Between` on the `Coord` dimension)

**Comment by rafaqz** [comment]
Yeah, nested dimensions is your own specific thing. There is no dispatch for that.

This is the idea, but it wont work - dims are parametric types.
```
function DimensionalData._dims2indices(c::Coord, sel::Coord{Lat{Between}}, emptyval = Colon())
```
You would need:
```
function DimensionalData._dims2indices(c::Coord, sel::Coord{<:Lat}, emptyval = Colon())
```

**Comment by Datseris** [comment]
looooooooooooooooool of course dimensions are parametric types
```julia

function DimensionalData._dims2indices(c::Coord, sel::Coord{ <: Lat{ <: Between}}, emptyval = Colon())
    l1, l2 = sel.val.val.val
    return coord_latitudes_between(c, l1, l2) # this is Vector{Int}
end
``` 
this works.

**Comment by Datseris** [comment]
thanks a lot!

**Comment by rafaqz** [comment]
@Datseris I had to make a few changes to `sel2indices` and `_sel2indices` for 0.15. Hopefully it doesn't affect this, but it may.

I'm going to try and work towards making `dims2indices`, `sel2indices` more stable as an unexported pseudo-interface, and maybe for 1.0 (whenever that can happen) we can make them part of the real interface so this kind of extension is a little more user friendly. But I don't think they're quite ready for that yet.
