### ISSUE TITLE
Cannot mutate a `DimArray` using named indexing?

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#220]
If I have

```julia
julia> using DimensionalData

julia> A = DimArray(rand(2, 3), (X, Y));
```

how would I set, e.g. `A[Y=1]` to a specific value?

I thought `A[Y=1] .= 7.45` should work but might be missing something:

```julia
julia> A[Y=1] .= 7.45
ERROR: MethodError: no method matching dotview(::DimArray{Float64,2,Tuple{X{Base.OneTo{Int64},NoIndex,NoMetadata},Y{Base.OneTo{Int64},NoIndex,NoMetadata}},Tuple{},Array{Float64,2},NoName,Nothing}; Y=1)
Closest candidates are:
  dotview(::Any...) at broadcast.jl:1160 got unsupported keyword argument "Y"
  dotview(::BitArray, ::BitArray) at broadcast.jl:1130 got unsupported keyword argument "Y"
Stacktrace:
 [1] top-level scope at REPL[103]:1
```

It works if I do e.g. `A.data[1, :] .= 7.45` but this seems against the DimensionalData.jl spirit.

**Comment by ali-ramadhan** [comment]
Ah never mind

```julia
A[Y(1)] .= 7.45
```

works.

Maybe this is a consequence of the two different syntax options (somewhat discussed in https://github.com/rafaqz/DimensionalData.jl/issues/197?).

**Comment by rafaqz** [comment]
I think we actually need a `Base.dotview` method. NamedDims.jl has that its just never come up for me until now.
