### ISSUE TITLE
`DimStack` for multiple layers of data that do not necessarily share dimensions?

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#221]
A very useful feature of `GeoData.AbstractGeoStack` is that the layers of the stack do not have to share dimensions. This makes it possible to load, analyze, and plot certain simulation data, e.g. from a staggered grid (aka Arakawa C-grid).

The current implementation of `DimensionalData.DimStack` seems to only support layers that share dimensions. I was wondering if this restriction can be relaxed or would a new `DimStack` type need to be defined?

Does it make sense to allow for layers that do not necessarily share dimensions?

**Comment by rafaqz** [comment]
Yeah the idea is to merge the functionality so `DimGeoStack` inhetits from `DimStack`. Im edging towards that, but its not so easy.

1. We need to track the list of dims for each layer so they can actually share them - in geodata they are loaded again for each layer. So there would be all the dims, and the dims a layer actually uses.
2. We need to work out the tables interface. When arrays are all the same dims they're the same length. When they are different we will need to loop them. And tables columns are indexable, not itetators. So its a little difficult to do lazily. But we can maybe use the same stride trick used on `DimColumn`.
3. `DimStack` maps methods like mean etc over all layers. We need to make sure this works with difgerent size layers (it should)

**Comment by rafaqz** [comment]
See #202
