### ISSUE TITLE
@dim cannot be used to export new dimensions

### ISSUE THREAD

**Issue by haberdashPI** [rafaqz/DimensionalData.jl#23]
MWE:

```julia
julia> module Foo
       using DimensionalData; using DimensionalData: @dim
       @dim Bar "Bar"
       export Bar
       end

julia> using .Foo

julia> DimensionalArray(rand(10),(Bar(1:10),))
ERROR: UndefVarError: Forward not defined
Stacktrace:
 [1] Bar(::UnitRange{Int64}) at /Users/davidlittle/.julia/packages/DimensionalData/sszkE/src/dimension.jl:192
 [2] top-level scope at REPL[3]:1
```

This looks like an issue with macro hygiene. Pretty sure I know how to fix it. I don't have a lot of time at the moment with a newborn in the house: if you don't end up getting to it yourself in a few weeks I can probably fix it by then.

**Comment by rafaqz** [comment]
Thanks for the clear example., I suspected there was an issue with that. Will probably get to it before then.

**Comment by rafaqz** [comment]
I actually can't replicate this. Are you using the latest master?

Also how are you calling `DimensionalArray` outside of Foo without using `DimensionalArray` ?

**Comment by haberdashPI** [comment]
Ah yes, my apologies. This works fine on master. I was using the latest tagged version.

**Comment by rafaqz** [comment]
There a a lot of changes to grids coming up so master might be a bit scary for the next few weeks. I'll tag the current state.

**Comment by haberdashPI** [comment]
Ah yes, very sorry for the noise here. It is all working for me now. Guess sleep deprivation is affecting me more than I think.
