### ISSUE TITLE
mean using Ti dimension throws MethodError: no method matching *(::Dates.CompoundPeriod, ::Int64)

### ISSUE THREAD

**Issue by brwst** [rafaqz/DimensionalData.jl#259]
I was bitten by this on a fairly well-trodden dataset (actually the full ERSSTv5 monthly mean dataset), so I attempted to recreate the error by using the ERSSTv5 long term monthly mean dataset [found in the tests](https://github.com/rafaqz/GeoData.jl/blob/a4696aaa224e6db933871daac7fd1ea32de630fd/test/sources/ncdatasets.jl#L96-L101).

```julia
using Test, Dates, Statistics
using GeoData, NCDatasets

ncrevlat = "sst.mon.ltm.1981-2010.nc"
ncrevlatarray = NCDstack(ncrevlat; childkwargs=(missingval=-9.96921f36,))[:sst]
@test order(dims(ncrevlatarray, Y)) == Ordered(ReverseIndex(), ReverseArray(), ForwardRelation())
@test ncrevlatarray[Y(At(40)), X(At(100)), Ti(1)] == missingval(ncrevlatarray)
@test ncrevlatarray[Y(At(-40)), X(At(100)), Ti(1)] == ncrevlatarray[51, 65, 1] == 14.5916605f0
@test val(span(ncrevlatarray, Ti)) == Month(1)
```

These tests pass. However, computing the mean of the `ncrevlatarray` over the time dimension errors:

```julia
julia> mean(ncrevlatarray, dims=Ti)
ERROR: MethodError: no method matching *(::Dates.CompoundPeriod, ::Int64)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  *(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:88
  *(::StridedArray{P, N} where N, ::Real) where P<:Period at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Dates/src/deprecated.jl:44
  ...
Stacktrace:
  [1] _reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:435 [inlined]
  [2] _reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:426 [inlined]
  [3] _reducedims(dim::Ti{Vector{DateTime}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Dates.CompoundPeriod}, Points}, Metadata{:NCD, Dict{Symbol, Any}}}, #unused#::Type{Ti})
    @ DimensionalData ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:417
  [4] map
    @ ./tuple.jl:233 [inlined]
  [5] map(f::typeof(DimensionalData._reducedims), t::Tuple{X{Vector{Float32}, Mapped{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float32}, Points, EPSG, EPSG}, Metadata{:NCD, Dict{Symbol, Any}}}, Y{Vector{Float32}, Mapped{Ordered{ReverseIndex, ReverseArray, ForwardRelation}, Regular{Float32}, Points, EPSG, EPSG}, Metadata{:NCD, Dict{Symbol, Any}}}, Ti{Vector{DateTime}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Dates.CompoundPeriod}, Points}, Metadata{:NCD, Dict{Symbol, Any}}}}, s::Tuple{Nothing, Nothing, UnionAll})
    @ Base ./tuple.jl:236
  [6] _reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:410 [inlined]
  [7] _reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:409 [inlined]
  [8] _reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:408 [inlined]
  [9] reducedims
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/primitives.jl:406 [inlined]
 [10] _mean(A::GeoArray{Float32, 3, Tuple{X{Vector{Float32}, Mapped{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float32}, Points, EPSG, EPSG}, Metadata{:NCD, Dict{Symbol, Any}}}, Y{Vector{Float32}, Mapped{Ordered{ReverseIndex, ReverseArray, ForwardRelation}, Regular{Float32}, Points, EPSG, EPSG}, Metadata{:NCD, Dict{Symbol, Any}}}, Ti{Vector{DateTime}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Dates.CompoundPeriod}, Points}, Metadata{:NCD, Dict{Symbol, Any}}}}, Tuple{}, Array{Float32, 3}, Symbol, Metadata{:NCD, Dict{Symbol, Any}}, Float32}, dims::Type; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DimensionalData ~/.julia/packages/DimensionalData/KTN1Y/src/methods.jl:21
 [11] _mean
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/methods.jl:21 [inlined]
 [12] #mean#216
    @ ~/.julia/packages/DimensionalData/KTN1Y/src/methods.jl:16 [inlined]
 [13] top-level scope
    @ REPL[15]:1
```

where

```julia
julia> dims(ncrevlatarray, Ti)
Dimension Time (type Ti):
val: DateTime[0000-12-30T00:00:00, 0001-01-30T00:00:00, …, 0001-10-30T00:00:00, 0001-11-29T00:00:00]
mode: Sampled: Ordered Regular Points
metadata: Metadata{:NCD, Dict{Symbol, Any}}(Dict{Symbol, Any}(:avg_period => "0030-00-00 00:00:00", :ltm_range => [66109.0, 77035.0], :axis => "T", :standard_name => "time", :long_name => "Time", :prev_avg_period => "0000-01-00 00:00:00", :interpreted_actual_range => "0001/01/01 00:00:00 - 0001/12/01 00:00:00", :delta_t => "0000-01-00 00:00:00", :units => "days since 1800-1-1 00:00:00", :climo_period => "1981/01/01 - 2010/12/31"…))
type: Ti{Vector{DateTime}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Dates.CompoundPeriod}, Points}, Metadata{:NCD, Dict{Symbol, Any}}}
```

Indeed the times are associated with a `Dates.CompoundPeriod`, but I'm not sure why that is so. The dataset times are regular monthly intervals and the times themselves are `Dates.DateTime` values. Is there a metadata inconsistency in this NetCDF file?

I'm new to the GeoData/DimensionalData environment, so I'm not sure what to look for here. I've also read through the DimensionalData docs but nothing is jumping out at me.

Thanks for the package, nice to have such indexing capabilities for spatial data in Julia.

**Comment by rafaqz** [comment]
The other question is: why is NCDatasets/CFTime giving us a `CompoundPeriod` for a single month. That should probably be fixed as well.

**Comment by brwst** [comment]
Thanks a lot, the MethodError and stacktrace make more sense to me now.

I agree, I couldn't come up with a good reason why `*` wasn't already implemented in `Base` for `CompoundPeriod` - though it seems there may be an open pull request that adds `*` for `CompoundPeriod` and `Real` at https://github.com/JuliaLang/julia/pull/36525?

**Comment by rafaqz** [comment]
Hopefully that gets merged one day...

But it seems you actually found 2 bugs, the other in GeoData when loading the step size in the first place.

To clarify that, the metadata inconsistency is from reading (non CF standard) time unit data that is in a lot of netcdf files - otherwise we don't have a step size and have to treat the index as irregular, which is annoying. But the way it's parsed has to allow for compound periods because it's a possibility. See:
https://github.com/rafaqz/GeoData.jl/blob/95e1802f8ef041000fc1f27c5b77b1708dd3433b/src/sources/ncdatasets.jl#L382-L394

We just need to check that if there is only one period in the periods vector, to take that instead of the `CompoundPeriod`. Which should be 99% of the time.

**Comment by brwst** [comment]
Makes sense, it's definitely tedious work to infer step sizes or grid spacings that aren't contained or defined outright in the file metadata.

Thanks for linking to the code, I finally understand where the `CompoundPeriod` is coming from. It's being created on https://github.com/rafaqz/GeoData.jl/blob/95e1802f8ef041000fc1f27c5b77b1708dd3433b/src/sources/ncdatasets.jl#L391, even if there is only one non-zero period value (such as the test data with `:delta_t => "0000-01-00 00:00:00"`).

```julia
using Dates

julia> typeof(Month(1))
Month

julia> Period(Month(1))
1 month

julia> typeof(Month(1) + Day(0))
Dates.CompoundPeriod

julia> typeof(Year(0000) + Month(01) + Day(00) + Hour(00) + Minute(00) + Second(00))
Dates.CompoundPeriod
```

I guess the tricky thing in `_parse_periods` is that there will always be six periods in the `periods` vector when parsing the `:delta_t` or `:avg_period` metadata since zeros are valid periods. Maybe something similar to this could work?

```julia
julia> vals = (0, 1, 0, 0, 0, 0)
(0, 1, 0, 0, 0, 0)

julia> periods = (Year, Month, Day, Hour, Minute, Second)
(Year, Month, Day, Hour, Minute, Second)

julia> nonzero_periods = findall(!iszero, vals)
1-element Vector{Int64}:
 2

julia> if length(nonzero_periods) == 1
           idx = nonzero_periods[1]
           periods[idx](vals[idx])
       elseif length(vals) == length(periods)
           sum(map((p, v) -> p(v), periods, vals))
       end
1 month
```

**Comment by brwst** [comment]
Ah, just saw the PR at https://github.com/rafaqz/GeoData.jl/pull/161, should have been looking (and typing) over there instead.
