### ISSUE TITLE
"No dims found" when operating on mean/ selecting dims by keyword with CoordMode coordinates.

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#263]
MWE:
```
using DimensionalData, StaticArrays, Random

c = [rand(SVector{2, Float64}) for i in 1:100]
t = 0:0.1:10

d = (Coord(c, (DimensionalData.X, DimensionalData.Y)), Ti(t))
a = rand(length.(d)...)

A = DimArray(a, d)

B = mean(A; dims = Coord)
```
```
ERROR: No dims found
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] dims(#unused#::Nothing)
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\dimension.jl:172
  [3] _reducedims (repeats 3 times)
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:413 [inlined]
  [4] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:412 [inlined]
  [5] _reducedims(dim::Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, #unused#::Type{Coord})
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:421
  [6] map(f::typeof(DimensionalData._reducedims), t::Tuple{Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, Ti{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}, NoMetadata}}, s::Tuple{UnionAll, Nothing})      
    @ Base .\tuple.jl:233
  [7] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:414 [inlined]
  [8] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:413 [inlined]
  [9] _reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:412 [inlined]
 [10] reducedims
    @ ~\.julia\packages\DimensionalData\BLGYA\src\primitives.jl:410 [inlined]
 [11] _mean(A::DimArray{Float64, 2, Tuple{Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, NoMetadata}, Ti{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, Sampled{Ordered{ForwardIndex, ForwardArray, ForwardRelation}, Regular{Float64}, Points}, NoMetadata}}, Tuple{}, Matrix{Float64}, NoName, NoMetadata}, dims::Type; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DimensionalData ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:21
 [12] _mean
    @ ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:21 [inlined]
 [13] #mean#238
    @ ~\.julia\packages\DimensionalData\BLGYA\src\methods.jl:16 [inlined]
 [14] top-level scope
    @ ~\Desktop\mwe.jl:11
 [15] eval
    @ .\boot.jl:360 [inlined]
```

This falls down to the function:
```
DimensionalData.reducedims(A, Coord)
```

As this is currently a completely stopper of my workflow, any tip on a quick fix would be super-duper appreciated :(

**Comment by Datseris** [comment]
Found it! Adding the following signature:
```julia
@inline _reducedims(mode::CoordMode, dim::Dimension) = rebuild(dim, Base.OneTo(1), NoIndex())
```
Solves the problem. The question is, is the `NoIndex()` appropriate here? I guess the actual index mode doesn't really matter for an empty dimension, right?

**Comment by rafaqz** [comment]
We should probably decide what the correct meaning of reducing a `Coord` is. What is the one value that is left? 

When you reduce a `Sampled` index the remaining value is the start/middle/end (depending on original locus) with a step size covering the whole original range. With a `Coord` nothing like that seems to make sense.  But making Coord `Noindex` will break some things currently.So it will need some thought.

**Comment by Datseris** [comment]
Can you explain why the `IndexMode` matters at all for a dimension without values? By definition this dimension cannot be indexed, right?

**Comment by rafaqz** [comment]
Because we are dispatching on `Coord` not `CoordMode`, which was a quick hack but its wrong. So `NoIndex` will be ignored.

It is also the information that will show in a plot.

**Comment by rafaqz** [comment]
Also length one has 1 value, in terms of dispatch its just another `AbstractArray`

**Comment by Datseris** [comment]
> We should probably decide what the correct meaning of reducing a Coord is. What is the one value that is left?

Does it really matter that much, given the reduction? Perhaps we can just pick the first value? This is a big bug for anyone using `Coord` and any statistical operation on it.

**Comment by Datseris** [comment]
Actually, I don't understand what you're saying. You can argue about the technicality of "length one has 1 value", because Julia will return an array of size `100x1` after `mean`. But this is done to satisfy type stability. The "reduced" dimension has no meaningful value. Why would you try to assign a value to it? I make a spatial average. It doesn't make sense to say "what space value should we attribute to this average". It doesn't have a space value.

If any value, I would use `nothing`.

**Comment by rafaqz** [comment]
Its not just for type stability. Its just how all the existing code works.

Dims have to contain an AbstractVector because all the code expects that. The vector/range has to be the same length as the array axis it matches, as that's an invariant rule for the package because it makes everything else easy. It also has to contain something. Using `At` should still match that something, It would be odd if was an error.

Regular dimensions do have semi-meaninful value after reduction, often the start/center/end of an interval that covers the original span of the array before the reduction.

In this case it's pretty much is meaningless, but if you want to use the existing code, you have to put something in a vector. And we want to use the existing code, that's how that PR was so short.

**Comment by Datseris** [comment]
> Regular dimensions do have semi-meaninful value after reduction, often the start/center/end of an interval that covers the original span of the array before the reduction

I don't really agree, but that's a rather subjective discussion that I don't want to pursue. Regardless you make a good point for why it is important to have an array value. The only two I can suggest is `[nothing]` or `[zero(eltype(coord.val))]`.

**Comment by rafaqz** [comment]
Ok, maybe zeros then, as we still have dimensions for the `Coord`. 

A PR would be nice, I'm pretty busy with other things currently and I don't use this.
