### ISSUE TITLE
Dimensions after reduction have the wrong coordinates

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#264]
It seems that dimensions want to retain their types so after taking a `mean` I expected the new dim to be `X: Float64[2.5]` since `mean(1:4) == 2.5` but instead it is `X: Int64[3]`.

Is this intentional for type stability or is it a bug?

```julia
julia> using Statistics, DimensionalData

julia> da = DimArray(randn(4), X(1:4))
4-element DimArray{Float64,1} with dimensions: 
  X: 1:4 (Sampled - Ordered Regular Points)
 -1.22385
 -1.35615
  1.09573
  1.43142

julia> mean(da, dims=X)
1-element DimArray{Float64,1} with dimensions: 
  X: Int64[3] (Sampled - Ordered Regular Points)
 -0.0132152
```

**Comment by rafaqz** [comment]
I think it's trying to take the midpoint, but just takes the nearest one. Probably because you cant take the mean of `DateTime`.

Its hard to be both consistent and also do the most obvious thing in situations like this. I'm not sure if I got it right with this one, but both taking the `Float64` mean of `Int` and choosing the closest `DataTime` could also seem be weird.

**Comment by ali-ramadhan** [comment]
Thanks for the explanation!

I guess reducing along a `Dimension{<:UnitRange}` could be special cased to produce a `Dimension{Array{Float64,1}}` if necessary. `Dimension{<:Array{DateTime}}` could also be special cased in a way that a `DateTime` mean could be computed. But yeah this seems like extra work for maybe not so much extra reward.

Since the behavior is generic, I should probably be using an `Array{Float64}` for the dimension values if I care about the dimension coordinates of reductions:

```julia
julia> da = DimArray(randn(4), X(collect(Float64, 1:4)))
4-element DimArray{Float64,1} with dimensions: 
  X: Float64[1.0, 2.0, 3.0, 4.0] (Sampled - Ordered Irregular Points)
  0.505011
 -0.665846
  0.0860938
  0.313163

julia> mean(da, dims=X)
1-element DimArray{Float64,1} with dimensions: 
  X: Float64[2.5] (Sampled - Ordered Irregular Points)
 0.0596054
```

I guess it's not really a bug so I'll close this issue but please feel free to reopen if there's something to address.

**Comment by rafaqz** [comment]
Its still a bit weird in the case of `mean` with `Int`. We can think about a better set of behaviors, a lot of things here are not entirely worked through because there's a really long tail on the small things that could be improved. So not high priority, but worth leaving open as a reminder.
