### ISSUE TITLE
Add Makie Plot recipes

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#275]
Probably Makie.jl is getting stable enough for this to be worth doing?

**Comment by tomchor** [comment]
I'd say Makie is pretty stable now, so it would be a nice addition. 

I'd be willing to try and code this up. Furthermore some repos that I work on/use have sided more with Makie than with plots, which gives me an incentive to do so.

Do you have any suggestions/guidelines or can point me in the right way?

**Comment by rafaqz** [comment]
See the PR over at Rasters.jl for inspiration. 

If MakieCore is not enough we can also do the weak dependency on Makie.jl for julia 1.9.

**Comment by tomchor** [comment]
> See the PR over at Rasters.jl for inspiration.
> 
> If MakieCore is not enough we can also do the weak dependency on Makie.jl for julia 1.9.

Sounds good. Here's a quick question: if Rasters.jl extends DimensionalData.jl, why not code all the Makie/Plots recipes in DimensionalData? I wouldn't think Rasters.jl would need any plotting capabilities per se.

**Comment by rafaqz** [comment]
Rasters is all about heatmaps and a lot of assumptions are made based on that.

Rasters also have known missing values and projections that need handling in some cases. DimensionalData.jl doesn't know about these things.

**Comment by rafaqz** [comment]
DimensionalData.jl can handle all the other plots, as it does now for Plots.jl.

Just not the spatial heat maps, they're quite field specific.
