### ISSUE TITLE
The README example conflicts Time with Dates.Time 

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#28]
```
julia> using DimensionalData: Time, X
WARNING: ignoring conflicting import of DimensionalData.Time into Main
```
Seems to me that `Time` is supposed to be a time axis, but results in conflicts with `Dates.Time`. As it currently stands the README example doesn't run and `Time` needs to be explicitly qualified.

I wonder, since this `Time` is supposed to be a thing used so often and `Dates.Time` is actually also a central thing, shouldn't the name of `DimensionalData.Time` be something just a bit different to avoid the conflict?

**Comment by rafaqz** [comment]
Yeah its a problem. There's just no other commonly used word to swap in so I gave up thinking about it.

**Comment by Datseris** [comment]
`TimeDim` might be an option, albeit a bit more verbose, signifying a "time dimension". Or, you could make `TimeDim` an alias of `Time` and export both, so that in the cases that `Time` doesn't conflict one can use the "short" version, but in the case where there is conflict, `TimeDim` is definitely less verbose than `DimensionalData.Time`.

**Comment by rafaqz** [comment]
I feel that TimeDim is getting us a little too close to AxisArrays levels of dim chars. 

```julia
A[T(1:10)]
A[Ti(1:10)]
A[Tim(1:10)]
A[Time(1:10)]
A[TimeDim(1:10)]
```

To me `T` feels the best, but `Ti` treads on less toes.

**Comment by Datseris** [comment]
I think the best idea is to make `Ti` an alias of `Time`, so that the "best" version can be used when there is no conflict, but when there is conflict one can use a different name while _still_ keeping all the dispatch purposes you use it for in e.g. GeoData.jl or elsewhere.
