### ISSUE TITLE
`mapslices` messes up the dimensions

### ISSUE THREAD

**Issue by anojo** [rafaqz/DimensionalData.jl#280]
It seems `mapslices` over a `DimArray` messes up the dimension indices over which the mapping happens.

### Example
```
da = DimArray(rand(5, 2), (Ti(1:5), Dim{:sth}(1:2)))
dam = mapslices(x -> x .+ length(x), da; dims=Dim{:sth})
dims(dam, :sth) |> collect
(* [2] *)
```

I would have expected `[1, 2]` as a result, right?

### Extra questions

I wonder, is there an alternative decent way to do these kinds of operations over specific dimensions? Like, applying a `fft` over `Ti` (which might turn reals into complexes). This seems to be an operation I want to do often. 

Also, is there a simple way to type-match dim arrays which contain a specific dimension(s)?

Thanks!

**Comment by rafaqz** [comment]
Yeah that's a bug. Dimension length should _always_ match the array axes.

Is there a reason `mapslices` isn't suitable besides this bug? There's also `eachslice`, and `dimwise` here. You can also just cut things up with `view` manually however you like. 

In GeoData.jl I've just written a `slice` method that cuts up arrays and stacks intro `series` (dimensional arrays of dimensional arrays/stacks)  using `view`, which can be useful to have nested dimensionality. I will move it here at some stage, but there are no `series` here yet.

> Also, is there a simple way to type-match dim arrays which contain a specific dimension(s)?

I'm not sure exactly what you mean here, but there are a bunch of low level methods like that in primatives.jl, `hasdim` will tell you if an object has a specific dimension. You can use `hasdim` to make a holy trait if you need that.

**Comment by anojo** [comment]
Given that it was a bug, I'm perfectly fine with `mapslices`. Thanks a lot for the detailed quick answer and bugfix!
