### ISSUE TITLE
Construction from sparsely sampled points

### ISSUE THREAD

**Issue by kiranshila** [rafaqz/DimensionalData.jl#288]
I can't seem to find this in the docs - but say I have some data that is representative of sparse samples from 3D space:
```julia
a = [1,2,3]
```
as in `f(1,0,0) = 1, f(2,0,0) = 2 ...`
If I then try to construct a dim array
```julia
x = [1,2,3]
y = [0,0,0]
z = [0,0,0]
A = DimArray(a,(X(x),Y(y),Z(z)))
```
I get
```
ERROR: DimensionMismatch("Array A has 1 axes, while the number of dims is 3")
```
Any advise? Thanks!

**Comment by rafaqz** [comment]
If you have 3 dimensions, `a` needs to have 3 axes of matching lengths. I should put that really clearly at the top of the readme. 

So I think you want to use a sparse array for `a`. Just leave the dimensions empty unless the have values you need to index that dont match the axes.

**Comment by kiranshila** [comment]
Sorry, saying `f(1,0,0)` wasn't clear. I was just trying to say that the points I have are representative of 3D data, but they aren't gridded, they are just arbitrary points from measured data.

Following what you said, I assume that means I need to grid the data somehow and then sparse-ify it before giving it to DimArray.

Thank you for your help!
