### ISSUE TITLE
Implement ArrayInterface.jl for Fast Strided Arrays

### ISSUE THREAD

**Issue by ParadaCarleton** [rafaqz/DimensionalData.jl#307]
DimArrays currently don't implement ArrayInterface.jl's array, so it won't work with LoopVectorization.jl:
> Okay, that's why. For an array type to be supported, it must implement the `ArrayInterface.jl` stride array interface (or `ArrayInterface` can define the appropriate methods itself).

> If `LoopVectorization.check_args(A) == true` and `LoopVectorization.stridedpointer(A)` returns a sensible result, then it should work. Currently the former returns `false` and the latter throws an error.

_Originally posted by @chriselrod in https://github.com/mcabbott/Tullio.jl/issues/125#issuecomment-910747954_

**Comment by rafaqz** [comment]
See #241. I've been too busy the last few months, and waiting for things to stabilize a little with ArrayInterface.jl. 

But a  PR would help.

**Comment by chriselrod** [comment]
This should be enough:
```julia
ArrayInterface.parent_type(::Type{<:AbstractDimArray{T,N,D<:Tuple,A}}) where {T,N,D,A} = A
```
