### ISSUE TITLE
Julia 1.4 errors

### ISSUE THREAD

**Issue by mauro3** [rafaqz/DimensionalData.jl#317]
The test suite errors on 1.4: https://github.com/mauro3/DimensionalData.jl/runs/3707606242?check_suite_focus=true#step:5:306

Adjust the version bounds to 1.5?

**Comment by rafaqz** [comment]
Yeah it should be, I started using the new kw syntax. Do you think its worth supporting 1.4 anymore?

**Comment by mauro3** [comment]
No, I think it's fine to drop Julia versions if you need a new feature.  In particular for a package which is still in development.
