### ISSUE TITLE
Display Axis Labels Alongside Columns/Rows?

### ISSUE THREAD

**Issue by ParadaCarleton** [rafaqz/DimensionalData.jl#318]
Currently, DimensionalData.jl displays axis labels separately from the data itself. This makes it hard to tell what each column means when a DimArray is displayed; it would be nice to have column labels displayed clearly above each column.

**Comment by rafaqz** [comment]
I'm open to someone writing this, but it's not a high priority for me in the near term. 

It will have to do output resizing to fit the window as it does currently.

**Comment by Datseris** [comment]
If you mean that you'd like to have something like this: 

https://github.com/mcabbott/AxisKeys.jl/blob/master/docs/readmeterminal.png

then I'd vote no, because this is information overload. It is better to simply `plot(A)` the dimensional array if you want advanced visualization, than to have so much extra text. That's the good thing with plot recipes.

**Comment by ParadaCarleton** [comment]
It doesn't have to be look the same; I think AxisKeys goes a bit more towards the "Show everything in colors" extreme than I'd like. The information I want is just these kinds of labels, so that I can tell which indices correspond to each element.
![image](https://user-images.githubusercontent.com/71727937/148447535-172d6b24-6c87-48b1-8c59-1454ebb0df55.png)

**Comment by Datseris** [comment]
Ah, okay I understand you better. Then I vote "okay" for this, because this _shouldn't_ actually use any extra space: first row and column are used for the labels. (I'm still totally happy with current printing)

**Comment by rafaqz** [comment]
Labels in dark grey would be good for this, and they don't need the brackets around them. Its good if you can easily find them of you want, but also easily ignore them and just look at the data.

**Comment by Datseris** [comment]
yeah, this sounds much, much better than the version of AxisKeys
