### ISSUE TITLE
`bounds` should return NamedTuple instead of Tuple

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#332]
Although this wont work on `LookupArray`. So `NamedTuple` from `Dimension`s, and `Tuple` from `LookupArray`s

**Comment by ParadaCarleton** [comment]
Maybe something similar should be done with `axes`, to make it easier to know which axis goes with which dimension?

**Comment by rafaqz** [comment]
It would be nice, but I'm not sure about messing with the return type of base methods? Someone will rely on a `Tuple` being the return value of `axes` (I know I do somewhere or other).

But `bounds` we own so it can be whatever. I'm not even sure its worth the distinction between `bounds(::LookupArray) => Tuple` and `bounds(::Dimension) => NamedTuple` to be honest.

**Comment by rafaqz** [comment]
We have `Extents.Extent` now returned from `extent(A)` which is basically a `NamedTuple`
