### ISSUE TITLE
Is a Union selector possible?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#342]
Hi,
In my work I very often do the operation "Select latitude -90 to -30 and 30 to 90", but no matter the format of my data, I always end up needing to write a custom function for such a selection because there is no combination of `At` or `Between`  etc. that just works.

I am actually hoping that I am missing something and I can actually write `A[UnionSelector(...)]` so that I keep using pure DimensionalData.jl syntax instead. But I am not sure. 

So I was wondering whether it is of any worth to consider using some kind of `Union` selector?

**Comment by rafaqz** [comment]
Thats an interesting use case. you can use `Where` with a function query.

**Comment by Datseris** [comment]
Ah. thanks. I didn't know of the where selector! That is kindof what I needed.

The use case is actually really common in climate science. These are the latitudes that define the "extratropics", and in planetary-scale climate one will typically make a distinction between the "tropics" (-30, 30) and the "extratropics".

**Comment by rafaqz** [comment]
But I also like the union idea, and it should only take a few lines to implement. `Union` is taken by Base, so we need a name:

```julia
A[Combined(Between(30, 90), Between(-30, -90))]
A[Cat(Between(30, 90), Between(-30, -90))]
```

I think `Cat` for contatenate makes it pretty clear what is happening, as it will be indices concatenated in the order you specify unless we do some magic to fix that and keep them in order.

**Comment by Datseris** [comment]
I don't like Cat, because `cat([1,2], [2,3])` will have two `2`, but this isn't what union means. Depends what you implement of course. If you implement union there aren't repeated indices, but if you implement cat, there are.

**Comment by rafaqz** [comment]
Well if you want Union, we'll need a name that means that that isn't Union, but is short.

There are some problems with it too... Im assuming you want the order to be maintained. Which union may not do.

**Comment by rafaqz** [comment]
How about `All` ? Like `All(30..90, -90..-30)`  (you can use intervals instead of `Between` now...)

**Comment by Datseris** [comment]
All sounds good. BTW `-90..-30` won't parse, you'd need `(-90)..(-30)`.

**Comment by rafaqz** [comment]
I think the `-90..` might parse but not `..-30`. Slightly annoying thing about elipses for intervals
