### ISSUE TITLE
`_slicespan` for irregular `AbstractTime` dimension errors

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#361]
I got this when I had a DateTime dimension that was ordered but irregular.

MWE:
```julia
using DimensionalData, Statistics

total_time = 1000
x = DimensionalData.X(cumsum(rand(10)))
y = DimensionalData.Y(cumsum(rand(10)))
t1 = DimensionalData.Ti(cumsum(rand(total_time)))
t2 = [Date(-26000 + ((i-1)÷12)*100, mod1(i, 12), 1) for i in 1:total_time] # centurial averages with seasonal cycle
t2 = DimensionalData.Ti(t2)

A1 = DimensionalData.DimArray(rand(10, 10, total_time), (x, y, t1))
A2 = DimensionalData.DimArray(rand(10, 10, total_time), (x, y, t2))

oidxs = [Ti(i) for i in 1:total_time]
# Works
r = map(i -> mean(view(A1, i)), oidxs)
# does not
r = map(i -> mean(view(A2, i)), oidxs)
```

With error: `InexactError: Int64(15.5)`

It comes from:
```
_slicespan(span::DimensionalData.Dimensions.LookupArrays.Irregular{Tuple{Nothing, Nothing}}, l::DimensionalData.Dimensions.LookupArrays.Sampled{Date, Vector{Date}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Irregular{Tuple{Nothing, Nothing}}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}, i::UnitRange{Int64})
    @ DimensionalData.Dimensions.LookupArrays C:\Users\m300808\.julia\packages\DimensionalData\Ma3Hp\src\LookupArrays\lookup_arrays.jl:461
```

specifically line  461:
```julia
(l[last(i) + 1] - l[last(i)]) / 2 + l[last(i)]
```

**Comment by rafaqz** [comment]
Thanks for the clean bug report, I actually thought I had fixed this, but seems not.

**Comment by rafaqz** [comment]
Ok the quick answer is to use `DateTime` rather than `Date` because a lot of math doesn't really work on `Date` as differences are returned in days, which are indivisible. 

I'll PR to use `div` instead of `\` for `Date`. It probably has some bad consequences for e.g. `cat` working properly later, but I guess its the best we can do.

**Comment by Datseris** [comment]
Thanks for the answer! 

I'm a bit confused though. I am reducing over the linear indices of the Time dimension. Why would it matter at all what the dimension is composed out of? The operation I am trying to do shouldn't be doing any computation involving date times.

Oh, is it because you need a "single number" to represented a "reduced dimension"? (which personally I do not think that such a number even makes sense to report).

**Comment by rafaqz** [comment]
Yeah, it's a little obscure. But when you slice a dimension it calculates the size of the slice. This has a few nice uses:
1. The plot title can show the slice details
2. `cat` can rejoin slices into the another array without specifying the dim values - because it can find the original step size in the `refdims` dim. Its pretty slick when you need it.

**Comment by Datseris** [comment]
> because it can find the original step size in the refdims dim. Its pretty slick when you need it.

That does sound slick. But here I have the situation that there is no "step size" because the ordering is irregular. In this scenario, the only way to recreate the dimension would be to simply store every element. I.e., not drop the dimension in the first place. That's fine with me, its not like dimensions cost a lot of memory. But still, I'd argue that even in this scenario there should not be any computation between `Date(Time)` instances, right?

I'm not arguing against the current design, that is totally fine for me. I just am trying to figure out where is it **necessary** that in my scenario of ordered but irregular points, the need for a computation between `DateTimes` arises.

**Comment by rafaqz** [comment]
There is actually a bug here - you have points, these calculations are only meant for intervals - for `Center` `Intervals` we need to calculate the `bounds` values of the dimension as they are not the values in the index.
