### ISSUE TITLE
rename dims name

### ISSUE THREAD

**Issue by kongdd** [rafaqz/DimensionalData.jl#368]
Dear @rafaqz ,

Taking the following example, I need to rename the dimension `:Y` to `:Z`. 
```julia
x = rand(X(10.0:40.0), Y(50))
name(x.dims) = (:X, :Z) # not work
```
Can I make it in `DimensionalData`?

**Comment by kongdd** [comment]
What I am trying to do is that: 
1. Read an 4d array from nc file into Raster;
2. Rename the Ti dimension into Band; Because Raster does not accept our band names. 
3. Write into tiff file

I was stucked in step2. Raster might can make some improvement to smooth the procedure to write tiff files. For example, if there is no Band dimension, just convert one.

**Comment by rafaqz** [comment]
`set` can do this:

```julia
set(x, Ti => Band)

# You can also do things like:
set(x, X => Intervals)
```

And yes GDAL can only save a third dimension as `Band`. You will also lose the sequence of times from the netcdf - tif cant store those.

We could possible do the conversion automatically, but the loss of information makes it something that would at least need a warning. And of course it will only extend to 3 dimensions, tif cant do 4.

**Comment by kongdd** [comment]
Got it. Thank u. 
I think giving a warning is a good option.

**Comment by rafaqz** [comment]
If you want to make a PR for that, it would be in the gdal source here:

https://github.com/rafaqz/Rasters.jl/blob/99d46c244286f80c8ff9c39cba6829b76ed22fa6/src/sources/gdal.jl#L64

You can instead convert the 3rd dimension to `Band` with `set`, as above. And use `@warn` so people know that happened.

**Comment by kongdd** [comment]
wondering whether there is a `set!` function? 
For lazy guys, `!set(x, Ti => Band)` is better than `x = set(x, Ti => Band)`.

**Comment by rafaqz** [comment]
There cant be a `set!` function because all these objects are immutable structs, we always have to rebuild everything into a new object. 

But this is usually better practice anyway - its functional style programming. It also means we can use them on GPUs, which is one of my use cases.

**Comment by kongdd** [comment]
Got it. Thanks for your explanation.

**Comment by rafaqz** [comment]
Also, it would also make the objects type unstable and slow if you could change any of these traits without rebuilding. A lot of my use cases are high performance models, so everything has to be type stable and fast - the promise of the package is very-cost abstractions.
