### ISSUE TITLE
Feature request: a way test implementations of AbstractDimArray

### ISSUE THREAD

**Issue by sefffal** [rafaqz/DimensionalData.jl#374]
Hi @rafaqz, and thanks for creating this package!

I’m working on a package that provides an implementation of an AbstractDimArray along with some additional fields: https://github.com/JuliaAstro/AstroImages.jl/pull/30 
I’d like a way to test that my implementation is correct.
My request is for a way to run this package’s tests, or a subset of them, on the downstream package to check the implementation.

If you think this is useful, I’m happy to lend a hand if you could suggest the right place to get started.

**Comment by rafaqz** [comment]
Yes, that's a good idea. This package really needs some formalisation. 

Currently Rasters.jl is the main implementation to copy.

**Comment by rafaqz** [comment]
Something as simple as this should be a good start:

```julia
using DimensionalData, Test

function test_dimarray(x::AbstractDimArray)
    @testset "types" begin
        @test parent(x) isa AbstractArray # Is this absolutely necessary?
        @test dims(x) isa DimensionalData.DimTuple
        @test refdims(x) isa Tuple
    end

    @testset "size" begin
        @test length(dims(x)) == ndims(x)
        @test map(length, dims(x)) === size(x) == size(parent(x))
    end

    @testset "rebuild" begin
        # argument version
        x1 = rebuild(x, parent(x), dims(x), refdims(x), metadata(x))
        # keyword version
        x2 = rebuild(x; data=parent(x), dims=dims(x), refdims=refdims(x), metadata=metadata(x))
        # all should be identical. If any fields are not used, they will always be `nothing`
        @test parent(x) === parent(x1) === parent(x2)
        @test dims(x) === dims(x1) === dims(x2)
        @test refdims(x) === refdims(x1) === refdims(x2)
        @test metadata(x) === metadata(x1) === metadata(x2)
    end
end
```

Just wondering wether to put this is the package, or make a DimensionalDataTests.jl to only use in CI?

**Comment by sefffal** [comment]
That looks like a good start! 
It could be a separate package, but something lighter weight could just be a script under DimensionalData.jl/tests.
If it's not included in runtests.jl, I think it will have no impact on users of DimensionalData.jl.
Downstream packages could then do something like:
```julia
using DimensionalData
include(joinpath(dirname(pathof(DimensionalData)),"tests/interfacetests.jl"))
test_dimarray(MyDimArray)
```

Just an idea, whatever works best for you.

**Comment by rafaqz** [comment]
Ok, I'll do that.

What we really need is an AbstractArrayTests.jl package that tests the whole Julia AbstractArray interface for correctness, so here we only have to test dimension indexing things.

**Comment by sefffal** [comment]
Your script was already useful, it found a method I hadn't yet implemented (keyword arg version of rebuild).
I think that's a sign it's a good approach!

**Comment by felixcremer** [comment]
We could put this functionality into a weak dependency on Tests.

**Comment by rafaqz** [comment]
I was thinking to write up an Interfaces.jl interface? This issue was half the inspiration to write that packagr I just never got back to add it.

It would also give a way to force correct updates when we make breaking changes here, or help when we add new optional behaviours.

We may as well just depend on Interfaces.jl, its tiny and has no deps.
