### ISSUE TITLE
Convenience way to check if a dimension exists in `dims(s)`

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#38]
Hi there, I've finally started using GeoData, things seems good so far. I have the following:

![image](https://user-images.githubusercontent.com/19669089/72819447-90ffb380-3c6d-11ea-82dd-26e5a34dfecf.png)

(which shows I have to work more on pretty printing, but that's for another PR). So as you can see `Longitude` is one of the dimensions. Of course, if one wants to be precise, they have to understand that "Longitude" is just a name. The _actual_ dimension is `Lon`. 

What I am currently missing is a simple way to check if a "dimension" (whatever this means) is in the dimensions of a given DimensionalArray. For example:

```
julia> "Longitude" ∈ dims(s)
false

julia> Lon ∈ dims(s)
false
```

I propose that we make a simple nice function `hasdim(s, dim)` in both of the above examples would return `true`. For the string case, it is obvious, one can use `dim \in name.(dims(s))`. But for the second case, I must admit I find it really hard... This is in general confusing for me:
```
julia> typeof(Lon)
UnionAll

julia> supertype(ans)
Type{T}

julia> Lon <: Dim
false
```
what _is_ `Lon`???

**Comment by Datseris** [comment]
If you can explain to me how to do the second half of what I propose, I'll do a PR.

**Comment by Datseris** [comment]
Haha! After some more searching I think I have found the answer!!!!

```
julia> Lon <: AbstractDimension
true

julia> typeof(dims(s)[1]) <: Lon
true
```

which means that I can just check if `any` in the dims satisfy this relation.

**Comment by rafaqz** [comment]
There is already a [hasdim](https://github.com/rafaqz/DimensionalData.jl/blob/master/src/primitives.jl#L168) method :)

Maybe we could export it. `dims(A, X)` gets specific dims. Read through primitives.jl there is a bunch of methods like this in there.

So closing this as already implemented :)

**Comment by Datseris** [comment]
well that does it, my next PR will make a proper documentation. Probably over the weekend.

By the way what is your take on having this package in an org, probably along GeoData? I've been talking with other devs on how we should use this package, yet we all converge to the absence of documentation as a big hit. Maybe welcoming more contributors is needed.

**Comment by rafaqz** [comment]
Docs would be amazing!

At this stage this package and GeoData.jl will stay in my account as I use it for most of my paid work and my other research packages, so I need to be the benevolent dictator until it's solid for my main use cases.

Also from the other threads you have probably read there are differing opinions on how this kind of package should work, so collectivising them is kind of premature and more work than it's worth. But if it makes it through the inevitable culling of dimensional array packages (I think it will) it will eventually go into a group.

**Comment by Datseris** [comment]
> But if it makes it through the inevitable culling of dimensional array packages (I think it will) it will eventually go into a group.

Great, that is fair and is what I was looking for. At the moment it seems you have very valid reasons to keep it here, which I honestly agree with. I would be skeptical though if most of Julia's climate community ends up using this package while it still remains group-less, which you also seem to agree. Thanks for clarifying.
