### ISSUE TITLE
`Dimensions.comparedims` but for indices?

### ISSUE THREAD

**Issue by sethaxen** [rafaqz/DimensionalData.jl#388]
`Dimensions.comparedims` checks dim names and lengths of indices but not the values of the indices:
```julia
julia> Dimensions.comparedims(Dim{:a}(1:10), Dim{:a}(1:9))
ERROR: DimensionMismatch("Found both lengths 10 and 9 for Dim{:a}")
...

julia> Dimensions.comparedims(Dim{:a}(1:10), Dim{:a}(2:11))
Dim{:a} 1:10
```
This can cause mismatched indices to be missed. Checking indices would be more expensive than just dims; would it make sense to have a method like `Dimensions.compareindex` that if compares dimensions and indices for provided objects?

**Comment by rafaqz** [comment]
Comparedims has undocumented keyword arguments to do this:

https://github.com/rafaqz/DimensionalData.jl/blob/cddea7b364b2ed7d71abc00e6b8e4207d2c5bb5d/src/Dimensions/primitives.jl#L485

Try the `val=true` keyword, it may work.

**Comment by sethaxen** [comment]
Works for me! Could these keywords be made part of the API?

**Comment by rafaqz** [comment]
Yes we could add them. Need to remove `metadata` as using it is a bug now. Maybe better keyword names too.

**Comment by rafaqz** [comment]
These are now documented.
