### ISSUE TITLE
How to get the value of a dimension by _name_ from a DImensionalArray?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#39]
I have a nice dimensional array, that has dimensions
![image](https://user-images.githubusercontent.com/19669089/72820126-ba6d0f00-3c6e-11ea-96ea-9cd0ee1f354d.png)

At the moment, if I want to get the _value_ of the i-th dimension, I can do `dims(s)[i].val`. But, how do I get the dimension's value by qualifying the dimension type?

Like, I want the values of the `Lon` dimension of `s`. 

Related with #38 .

**Comment by rafaqz** [comment]
Just do `dims(A, X)` or `dims(A, (X, Y)) etc.

Notice that all the methods in primitives are recursive so they cover a lot of functionality.
