### ISSUE TITLE
Implementing the TableTraits interface

### ISSUE THREAD

**Issue by sethaxen** [rafaqz/DimensionalData.jl#390]
Not every package that uses tables uses the Tables interface. Notably, the QueryVerse packages and the Julia VSCode plug-in all use the TableTraits interface instead, so it's useful to implement both.

Here is one way to implement the interface for DimensionalData, modeled after [how DataFrames does it](https://github.com/JuliaData/DataFrames.jl/blob/main/src/other/tables.jl).

```julia
function IteratorInterfaceExtensions.getiterator(da::AbstractDimArray)
    return Tables.datavaluerows(Tables.columntable(da))
end
IteratorInterfaceExtensions.isiterable(da::AbstractDimArray) = true
TableTraits.isiterabletable(da::AbstractDimArray) = true

function IteratorInterfaceExtensions.getiterator(ds::AbstractDimStack)
    return Tables.datavaluerows(Tables.columntable(ds))
end
IteratorInterfaceExtensions.isiterable(ds::AbstractDimStack) = true
TableTraits.isiterabletable(ds::AbstractDimStack) = true
```

**Comment by rafaqz** [comment]
Nice. Guessing these deps have minimal startup time?

If so, a PR adding this would be great.
