### ISSUE TITLE
The examples for `@dims` errors

### ISSUE THREAD

**Issue by alecloudenback** [rafaqz/DimensionalData.jl#397]
The [example in the docs](https://github.com/rafaqz/DimensionalData.jl/blob/65da9886ed625a7dd5c44de64dec9c310249a1bb/src/Dimensions/dimension.jl#L365) errors:

```julia
@dim Lat YDim "latitude"
```
gives
```
UndefVarError: @dim not defined
```

Or when qualified:

```julia
DimensionalData.Dimensions.@dim Lat DimensionalData.Dimensions.YDim "latitude"
```
gives:
```
MethodError: no method matching dimmacro(::Symbol, ::Expr, ::Expr, ::String)
```

**Comment by rafaqz** [comment]
Yes, the docs are a bit out of data unfortunately. You need to import things to do lower level work like this now:

```julia
using DimensionalData: YDim, @dim
@dim Lat YDim "latitude"
```

**Comment by rafaqz** [comment]
Fixed
