### ISSUE TITLE
Implement * (or other unicode symbol) as in xarray

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#41]
In Python's xarray, if you have a 3D array A with dimensions (Lon, Lat, Time), and you have another array B with dimension (Lat,) (i.e. a Vector) you can do "dimension-wise" multiplication. This means, (and assuming that `size(A, Lat) == size(B, Lat)`) you can write:
```julia
A * B
```
which would multiply every element `A[:, i, :]` with `B[i]`. This is tremendously useful when multiplying a spatiotemporal field with a vector of probabilities, e.g. weighting a spatiotemporal distribution by the cosine of the latitude.

Yes or no?

**Comment by rafaqz** [comment]
That is interesting. Shouldn't be too hard to implement, feel free to have a go.

Just remember that most of the core tools are defined in primitives.jl, you shouldn't have to do much yourself.

**Comment by rafaqz** [comment]
I'm wondering if this is compatible with current behaviour of `*` on arrays. Will there be any circumstances where `*` will currently work (ie not error because of size mismatch etc) but this change will produce a different result?

If so we may need to add a method for this.

**Comment by Datseris** [comment]
I have concluded that using the symbol `*` is not a good idea, as it will naturally try to compare itself with the behavior of pure arrays, which I don't think makes much sense. I will use the symbol `\otimes` instead.

**Comment by rafaqz** [comment]
Would it be possible to generalise this a little more? We could write this so you can us +,-,/,|,& etc as well using the same methods. Something like:

`somemethod(f, A, B)`

Where `f` can be `*`, or anything else that accepts two args. But I'm not sure what to call the method...

**Comment by Datseris** [comment]
`dimensionwise` ?

**Comment by rafaqz** [comment]
That gets the meaning across really well. `dimwise` would be shorter but maybe less clear, I'm not sure.

**Comment by Datseris** [comment]
Hi, I was going to start working on that today, but I saw that there is #48 and #49 , which are not _directly_ relevant, but still good to know and should be taken into account to write the most clear source code.

So I'll wait for them to be done and then I'll start doing this next week. In the meantime I'll start a Documentation PR that builds more proper docs based on Documenter.

**Comment by Datseris** [comment]
nice, I've solved this. Implemented it and tested it in my code and it works. Will PR it once #48 and #50 are merged, because I don't want to be constantly doing rebasing stuff.

**Comment by ivirshup** [comment]
@Datseris, when you say `A * B`, is that python syntax or have you translated? I like the idea of being able to use `xarray`'s `A * B` (I'd call this "broadcasting"), but I'm not as much a fan of their `A @ B`.

**Comment by Datseris** [comment]
A*B is Python syntax, but as I said elsewhere it does radically different thing that what `*` does here now, after Raf merged the `*` PR. Once you are done with #48 we will get it here as well, but not with `*`, with `dimewise` instead.

**Comment by ivirshup** [comment]
Ah, I had thought you were thinking of matrix multiplication. I think `xarray`'s `A * B` would make more sense as `A .* B` in Julia. So, something like `@dimwise A .* B` for automatic alignment, since it's difficult to pass `.*` as an argument to a function.

**Comment by rafaqz** [comment]
> Ah, I had thought you were thinking of matrix multiplication. I think xarray's A * B would make more sense as A .* B in Julia. So, something like @dimwise A .* B for automatic alignment, since it's difficult to pass .* as an argument to a function.

I like just passing `*` and avoiding the macro. Did you have a go at this @Datseris?

**Comment by Datseris** [comment]
Yeah I have this solved in my own code. I have implemented the `dimwise` function as originally described, it works for any binary `f`.

**Comment by rafaqz** [comment]
`dimwise` was implemented in #151
