### ISSUE TITLE
How to select a dimension by indices (if possible)?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#42]
Let's say I have the scenario where I want to select one of the dimensions of my data by indices, instead of values (like e.g. take the first 10 time points, but without necessarily knowing if "Time" is the first dimension).

Is this possible? To my understanding `At, Near, Between` use values. If not possible, would this be supported with another selector `ByIndex` or some sorts?

**Comment by rafaqz** [comment]
That's what `A(X(1), Y(2:5))` does.

**Comment by Datseris** [comment]
Ah cool!

**Comment by rafaqz** [comment]
I really need to get all this clearer in the docs these questions are really useful.

**Comment by Datseris** [comment]
Don't worry, I'll soon have a documentation PR here but I first have to PR https://github.com/rafaqz/DimensionalData.jl/issues/41 because I need it for the job. Then the docs come.
