### ISSUE TITLE
Subsetting repeated dimensions

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#430]
When indexing into an array with repeated dimension names, only the first dimension is indexed. E.g.

```julia
julia> using DimensionalData
julia> A = rand(1:100, X(5), X(5))
5×5 DimArray{Int64,2} with dimensions: X, X
 19  80  85  12  28
  8  59  98  39  40
 14  87  62  69  55
 95  31  94  54  81
 17  84  87  13  69

julia> A[X(3:5)]
3×5 DimArray{Int64,2} with dimensions: X, X
 14  87  62  69  55
 95  31  94  54  81
 17  84  87  13  69
```

In a previous version, this would have indexed both `X` dimensions, see: https://github.com/rafaqz/DimensionalData.jl/issues/46#issue-557264711. This is the behavior I would have expected when order of indexing statements doesn't matter.

Is this change intentional?

(also hey, hope your pandemic went alright Raf!)

**Comment by rafaqz** [comment]
Hey good to hear from you, and you too! (In Denmark these days)

Sorry about that it's an unintentional change, so a bug. Maybe there is no test for it.

**Comment by rafaqz** [comment]
Now that I'm running your example... I think it was maybe a bug before? With most other operations the doubled dimension is just accessed by order.

This works:
```julia
A[X(3:5), X(3:5)]
```

But it's up for debate. I think these behaviors are the result of lower level generalisation in `sortdims` or some other primitive method.

**Comment by rafaqz** [comment]
```julia
using DimensionalData
A = rand(1:100, X(5), X(5))
```
Just using the same dimension twice works, I think its better for that to be explicit anyway:
```jullia
julia> A[X(3:5), X(3:5)]
3×3 DimArray{Int64,2} with dimensions: X, X
 57  60  26
 44  95  54
  8  53  39
```
