### ISSUE TITLE
`cat` on Regular Points creates incorrectly typed indices

### ISSUE THREAD

**Issue by ParadaCarleton** [rafaqz/DimensionalData.jl#433]
The type for the new indices is wrong; they're typed as regular points, despite no longer being regular:
```
julia> da
3×4 DimArray{Int64,2} with dimensions: 
  Y Sampled{Int64} 10:10:30 ForwardOrdered Regular Points,
  Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points
     1  2  3  4
 10  1  2  3  4
 20  3  4  5  6
 30  5  6  7  8

julia> cat(da, da; dims=Y)
6×4 DimArray{Int64,2} with dimensions: 
  Y Sampled{Int64} Int64[10, 20, …, 20, 30] ForwardOrdered Regular Points,
  Ti Sampled{Int64} 1:4 ForwardOrdered Regular Points
     1  2  3  4
 10  1  2  3  4
 20  3  4  5  6
 30  5  6  7  8
 10  1  2  3  4
 20  3  4  5  6
 30  5  6  7  8
```
Two possibilities here, assuming we want to keep type stability:
1. Always assume `cat` on regular points generates irregular points, or
2. Throw an error when the regular points don't line up -- I think this makes more sense.

**Comment by rafaqz** [comment]
2 is good. We could also check and switch to irregular.

Not only is this Irregular but it repeats values, so is not a useful lookup at all. We would have to swap this to `NoLookup`.

**Comment by ParadaCarleton** [comment]
> 2 is good. We could also check and switch to irregular.
> 
> But not only is this example Irregular but it repeats values, so is not a useful lookup at all. We would have to swap this to `NoLookup`. Although I guess `Where` still works... maybe there needs to be a new order type `UnorderedRepeated()` or something.

I think it makes more sense to add an `@assert` condition, whenever constructing an index, that throws an error if indices are repeated. Repeated indices usually mean a mistake on the user's part, e.g. specifying the wrong dimension to concatenate along.

**Comment by rafaqz** [comment]
Sure  that makes sense too. If you want to implement any of these checks go for it.

**Comment by rafaqz** [comment]
Update: `cat` wont allow overlapping indices now - but `Regular` still does not convert to `Irregular` automatically
