### ISSUE TITLE
Metadata for dimensions

### ISSUE THREAD

**Issue by chriswaudby** [rafaqz/DimensionalData.jl#436]
Hi,

I've been following the development of this package for a while, and it's really useful - thank you!

I've got a question about attaching metadata to dimensions. This seems to change the way they behave:

```julia
julia> ax1=X(.1:.1:1)
X 0.1:0.1:1.0

julia> ax1[1:3]
X 0.1:0.1:0.3

julia> ax2=X(.1:.1:1,metadata=DimensionalData.LookupArrays.NoMetadata())
X

julia> ax2[1:3]
X
```

Are you able to comment on what's going on here? From what I've been able to gather from the code and documentation, the dimension data is stored in some sort of lookup array when metadata is present, but I don't really understand the logic behind this. Is there a simple way to extract the coordinate values as an array, as `parent()` does for the array data itself?

**Comment by rafaqz** [comment]
Yeah... youre actually just adding arbitrary keywords that get passed to a LookupArray later when you construct a `DimArray` with these dimensions, or whatever. `format` will analyse what you pass in to guess the LookupArray types.

Dimensions are just simple wrappers now, they don't have metadata. LookupArrays that a Dimension wraps have metadata.

Maybe try constructing e.g. `Categorical` or `Sampled` lookups arrays directly.

I know it's not the cleanest currently - these things used to be the same object. I've been meaning to get rid of this weirdness for a while by running `format` earlier but theres always something more urgent. 

So thanks for the bump I'll look at it soon.

**Comment by chriswaudby** [comment]
OK, that makes sense… Thanks for the clarification!
