### ISSUE TITLE
Constructing a similar AbstractDimArray for specific dimensions

### ISSUE THREAD

**Issue by sethaxen** [rafaqz/DimensionalData.jl#437]
I'm writing a generic method that takes a 3d `x::AbstractArray{<:Any,3}` and returns a `y::AbstractVector{T}`, where `axes(x, 3) === axes(y, 1)`. It's effectively a reduction but can't be computed with the existing reduction machinery.

I'd like to allocate the output in a way that preserves any named dimensions but without depending on DimensionalData. Currently the best I can do is
```julia
julia> x = DimArray(randn(10, 4, 2), (Dim{:draw}(1:10), Dim{:chain}(1:4), Dim{:var}([:a, :b])));

julia> T = Bool;

julia> y = similar(@view(x[begin, begin, :]), T)
2-element DimArray{Bool,1} with dimensions: 
  Dim{:var} Categorical{Symbol} Symbol[a, b] ForwardOrdered
and reference dimensions: 
  Dim{:draw} Sampled{Int64} 1:1 ForwardOrdered Regular Points,
  Dim{:chain} Sampled{Int64} 1:1 ForwardOrdered Regular Points
 :a  0
 :b  0
```

@devmotion suggested using the `similar(A, axes)` syntax documented in [Base](https://docs.julialang.org/en/v1/devdocs/offset-arrays/), but this is what we get:

```julia
julia> similar(x, (axes(x, 3),))
2-element Vector{Float64}:
 6.9364632819056e-310
 6.9364632819064e-310
```
It's not surprising this is a `Vector` since `axes` returns a tuple of `Base.OneTo`, and we don't even know which dimension these indices should correspond to. We could slice the first two axes, but this doesn't even work in Base:
```julia
julia> similar(parent(x), Bool, (axes(x, 1)[begin:begin], axes(x, 2)[begin:begin], axes(x, 3)))
ERROR: MethodError: no method matching similar(::Array{Float64, 3}, ::Type{Bool}, ::Tuple{UnitRange{Int64}, UnitRange{Int64}, Base.OneTo{Int64}})

Closest candidates are:
  similar(::AbstractDimStack, ::Any...)
   @ DimensionalData ~/.julia/packages/DimensionalData/KC0aG/src/stack/stack.jl:58
  similar(::AbstractArray, ::Type{T}, ::Union{Integer, AbstractUnitRange}...) where T
   @ Base abstractarray.jl:838
  similar(::Array, ::Type, ::Tuple{Vararg{Int64, N}}) where N
   @ Base array.jl:374
  ...
```

I'm wondering if there's a way to make `similar(x, (axes(x, 3),))` syntax work here. What if DimensionalData defined the following:
```julia
struct DimUnitRange{T,D<:Dim,R<:AbstractUnitRange{T}} <: AbstractUnitRange{T}
    dim::D
    range::R
end
Base.parent(r::DimUnitRange) = r.range
Dimensions.dims(r::DimUnitRange) = r.dim
Dimensions.dims(rs::Tuple{DimUnitRange,Vararg{DimUnitRange}}) = map(Dimensions.dims, rs)

# ... define necessary overloads for it to behave like the parent 
for f in [:firstindex, :lastindex, :axes, :length, :isempty, :first, :last]
    @eval @inline Base.$f(r::DimUnitRange) = $f(parent(r))
end
@inline Base.iterate(r::DimUnitRange, i...) = iterate(parent(r), i...)
@inline Base.getindex(r::DimUnitRange, i::Integer) = getindex(parent(r), i)

# use it for axes
Base.axes(da::AbstractDimArray) = map(DimUnitRange, Dimensions.dims(da), axes(parent(da)))

# overload similar
function Base.similar(A::AbstractDimArray, T::Type, shape::Tuple{DimUnitRange,Vararg{DimUnitRange}})
    data = similar(parent(A), T, map(parent, shape))
    return rebuild(A, data, Dimensions.dims(shape))
end
```

Then we have
```julia
julia> similar(x, Bool, axes(x))
10×4×2 DimArray{Bool,3} with dimensions: 
  Dim{:draw} Sampled{Int64} 1:10 ForwardOrdered Regular Points,
  Dim{:chain} Sampled{Int64} 1:4 ForwardOrdered Regular Points,
  Dim{:var} Categorical{Symbol} Symbol[a, b] ForwardOrdered
[:, :, 1]
     1  2  3  4
  1  0  0  1  0
  2  1  0  1  0
  3  1  1  0  0
  4  1  1  0  1
  5  1  0  0  0
  6  1  0  0  0
  7  0  0  0  1
  8  0  0  1  1
  9  0  1  1  0
 10  0  1  1  0
[and 1 more slices...]

julia> similar(x, Bool, (axes(x, 3),))
2-element DimArray{Bool,1} with dimensions: 
  Dim{:var} Categorical{Symbol} Symbol[a, b] ForwardOrdered
 :a  0
 :b  0
```

RE the concerns raised in https://github.com/rafaqz/DimensionalData.jl/blob/3087e3e445ddb57e3f02630d6077cff585a132ac/src/array/array.jl#L118-L121
I don't think these apply here. If a user is using this directly (not intended), they would need to manually set the dim and range to have compatible numbers of elements, or an error would automatically be raised if these did not match; no need to pad the indices to match the axes.

**Comment by rafaqz** [comment]
I like `DimUnitRange`! 

I thought of nearly the same thing until I got to that bit of the code.

Looks like it will have not real performance overheads either. PR ?

**Comment by sethaxen** [comment]
Yeah I don't think it will, and we can make sure by patterning it off of OffsetArrays. Sure I'll open a PR.
