### ISSUE TITLE
Incorrect dimensions after matrix multiplication

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#47]
My assumption here is that `x::DimensionalArray -> length.(dims(x)) == size(x)` should be true for enumerated dimensions. Here's an example:

```julia
using Dates, DimensionalData
using DimensionalData: Time, X
timespan = DateTime(2001):Month(1):DateTime(2001,12)
A = DimensionalArray(rand(12,10), (Time(timespan), X(10:10:100))) 

@assert length.(dims(A)) == size(A)
@assert length.(dims(A')) == size(A')

length.(dims(A * A')) == size(A * A')
# false
```

This seems right:

```julia
size(A * A')
# (12, 12)
```

But the first dimension is `X`, when it should be `Time`:

```julia
dims(A * A')
# (X: 10:10:100, Time: 2001-01-01T00:00:00:1 month:2001-12-01T00:00:00)
```

However, if both dimensions were `Time`, that would start leading to problems with #46.

**Comment by rafaqz** [comment]
There isn't actually a custom method for `*` yet that correctly handles dimensions. So the current dims are just an artefact of how `similar` works. Ie. they are wrong.

Are there any other methods like `*` that we should add? This is not really something I do with this package, as you can probably tell by now.

I guess it will be similar to my implementation of `cov` except the dim kept is always the first dimension?

**Comment by Datseris** [comment]
We discussed a bit what `A * B` could mean in #41 . Python's xarray does something radically different with what you present here @ivirshup , it does dimension-wise multiplication as discussed in #41 . 

It took me half an hour or so to finally figure out what `A * B` was doing in Python, which makes me think it is not really intuitive.

My opinion would be that this package should not support `A * B` as in general I think it is correct to say that it is undefined behavior. What would it mean for arbitrary `A * B` with arbitrary dimensions? And what if you do `A * B` where both are square but each have different dimensions?

I would vote that instead `A * B` should error for `A, B ::DimensionalArray`. In base Julia `a*b` with `a, b ::AbstractArray` generally errors and only works at very, very specific cases.

**Comment by rafaqz** [comment]
`*` should be supported if the dimensions match. It should error if they don't. We want to allow as much Base julia to work as possible when you can reasonably expect it to work.

**Comment by ivirshup** [comment]
I like both of these of these behaviors, and ideally would like to be able to choose between them. Behaving like a normal array should probably be the default. Maybe there could be a macro or context where the xarray style behaviour would be used? Something like `@match_dims`?

**Comment by Datseris** [comment]
I think we agreed on the name `dimwise` or `dimensionwise`, and it can be made for any function, `dimensionwise(f, A, B)`, that matches the dimensions and applies `f` across that matched dimension, see #41 .

**Comment by rafaqz** [comment]
@ivirshup let me know if this works enough for your needs. 

Unfortunately `*` working with `Adjoint` and `Transpose` will need a little more work.
