### ISSUE TITLE
1.0 plans

### ISSUE THREAD

**Issue by odow** [rafaqz/DimensionalData.jl#491]
Hi @rafaqz,

We're planning to integrate DimensionalData into JuMP as a weak dependency: https://github.com/jump-dev/JuMP.jl/pull/3413/.

You can see how it'd be used here: https://jump.dev/JuMP.jl/previews/PR3413/extensions/DimensionalData/. I think the integration works quite well.

One thing we are considering is the impact of future breaking changes. Are there any plans to release DimensionalData v1.0 (or v0.25)?

For this particular case, the impact is very minor, since I wouldn't expect you to break the two line function:
https://github.com/jump-dev/JuMP.jl/blob/74d513f2604c125d6c12c08f17a96764a188b069/ext/JuMPDimensionalDataExt.jl#L17-L18

It's more about limiting the scope for package incompatibilities if you're going to release v0.25, v0.26, v0.27 in short order.

**Comment by rafaqz** [comment]
Good to hear!

I have no current plans for breaking releases. Most likely it will be bug fixes and missing functionality only for quite a while now. 

Any breaks that have to be made in the next year are likely to be only technically breaking to rarely used subcomponents, rather than changes that will affect users or JuMP interop.

**Comment by odow** [comment]
Yeah it's more of a co-ordination issue for the package manager, rather than the particular code in JuMP.

If lots of packages start using DimensionalData and we don't all say on top of the `v0.24` -> 25 -> 26 transitions, then it'll be easy to end up with incompatibilities. If you lock in v1.0 (and don't then go v2, v3, etc) it's a lot simpler. 

If you are thinking of making a breaking release, perhaps you could tag me beforehand? Then everything should be smooth sailing.

**Comment by rafaqz** [comment]
Ok that makes sense. I'll tag you if/when there is a breaking release in future.
