### ISSUE TITLE
Don't export X,Y

### ISSUE THREAD

**Issue by sylvaticus** [rafaqz/DimensionalData.jl#493]
These are very general variable name, I don't think these should be exported.

Then this happens:

```
julia> using Rasters
julia> X
X
julia> X = 2
ERROR: cannot assign a value to imported variable Dimensions.X from module Main
Stacktrace:
[1] top-level scope
@ REPL[3]:1
```

**Comment by rafaqz** [comment]
Just dont use X from Rasters first and you can assign whatever you like to it. I fontvsee where thecreak problem ie
