### ISSUE TITLE
`name(Dim)` is Symbol and docstring says it should be String

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/DimensionalData.jl#494]
There is a mismatch for the name function between the docstring and the implementation where the docstring states, that it should return a string, but then it returns a Symbol.
I am not sure, whether it matters much in which way to resolve this mismatch.

```
help?> DD.name
  name(x) => String
  name(xs:Tuple) => NTuple{N,String}
  name(x, dims::Tuple) => NTuple{N,String}
  name(x, dim) => String

  Get the name of an array or Dimension, or a tuple of of either.

  Second argument dims can be Dimensions, Dimension types, or Symbols for Dim{Symbol}.

julia> ax = Dim{:n}(1:3)
Dim{:n} 1:3

julia> name(ax)
:n
```

**Comment by rafaqz** [comment]
Yeah it needs to be a Symbol for NamedTuple keys and Table columns. The doc must be old.

**Comment by felixcremer** [comment]
I prepare a PR to fix the docstring.

**Comment by rafaqz** [comment]
Did you have a PR for this?

**Comment by felixcremer** [comment]
Sorry, I had a branch but somehow didn't push it online.

**Comment by rafaqz** [comment]
No worries, just avoiding doing it myself if you have
