### ISSUE TITLE
println of a DimArray shows all values in the array

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/DimensionalData.jl#498]
When I use println to print a DimArray it does not show the nice formatted printing of the Axes but only prints the values in the array. This is a huge footgun, because it can lead to printing multi GB worth of data. 
I ran into it, when I wanted to print a subsetted array into a textfile to see the size of the dimensions, and then it printed the whole dataset into it. 

When we replace the Base.show method with the MIME type by the 2-arg method without the MIME type this works as expected. 
I can prepare a PR.

**Comment by rafaqz** [comment]
Yes I have just left the default `AbstractArray` behaviour. Raw `show` is usually not pretty printed.

You could also use `sprint` with `"text/plain"` instead of `print` ?

**Comment by felixcremer** [comment]
We do not want to change this behaviour in DimensionalData because we would like to see the values of small arrays. We should implement `show(io, A)` for YAXArrays and Rasters because the show methods do not hit the show of the underlying DiskArray.

**Comment by felixcremer** [comment]
We can just forward the `show(io, A)` function to the parent(A).

**Comment by rafaqz** [comment]
This is forwarded now:
https://github.com/rafaqz/DimensionalData.jl/blob/f5468f2d654d0d6dd9f4c27c9a45efd5222edbf8/src/array/show.jl#L21
