### ISSUE TITLE
Handle Transpose and PermuteDimsArray

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#5]
solutions: 
- define dims for them and reorder the dims tuple of the contained array to match the transpose.
- add a constructor for `Transpose(a::AbstractDimensionalArray)` that rewraps the Transpose in the dim array, as with SubArray in view.

As discussed in 
https://github.com/JuliaCollections/AxisArraysFuture/issues/1

**Comment by mcabbott** [comment]
Corresponding discussion about `PermuteDimsArray` in NamedDims, perhaps of interest: https://github.com/invenia/NamedDims.jl/pull/64#pullrequestreview-278386316

tl;dr is that people find it weird that a constructor not return something of its own type, but `transpose` is obviously no problem.

**Comment by rafaqz** [comment]
That pretty much sums it up. It's also good to keep wrapping the type with the dimensional type on the outside for any other methods people want to put on the array type and for dispatch. 

How do you compare the two approaches after playing with the implementation in NamedPlus?

**Comment by mcabbott** [comment]
Sorry I never replied. I think my answer is that it seems possible to make quite a long list of wrappers around your type work transparently, but it may be more hassle than it’s worth! 

My current attempt is  [AxisRanges.jl](https://github.com/mcabbott/AxisRanges.jl), which only tries to commute with NamedDims, which is much easier.

**Comment by rafaqz** [comment]
Yeah wrappers are a no go. I decided DimensionalArrays are "dominant" types and just always re-wrap things, which is much less work.
