### ISSUE TITLE
Further improve pretty printing of DimensionalArray

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#53]
Although the PR #33 improved the situation, much is left to be desired:

![image](https://user-images.githubusercontent.com/19669089/73654023-eb940900-468a-11ea-82de-220fb920e11b.png)

The printing of the dimensions is not optimal, too many elements are shown and they are taking multiple lines, which messes the alignment. The array data take up several pages when printed, which is also not so helpful.

No matter how much I hacked at it I couldn't make it work cleanly. I don't know why it worked cleanly for DynamicalSystems.jl.

Anyway, here is what I propose to make the situation better, which I can easily put in a PR:
1. For any dimension by default show at most 4 elements: first, second, end-1 and end, and put `...` in between.
2. For array data with dimension 3 or larger, only show the first 2D frame, i.e. `A[:, :, 1, 1, 1, 1,...]`.

This will make the printing both useful as well as readable.

**Comment by rafaqz** [comment]
Sounds good to me.

I think they should also be `Lat (Lattitude): Float32[0.5`: so the type name is shown first, as you pointed out somewhere else it's a little confusing as is.

**Comment by Datseris** [comment]
Yes good point. I was thinking about that and I thought another way to do this is to start with the normal name and then mention the type explicitly, as in 
```
Lattitude (type Lat): ...
```

**Comment by rafaqz** [comment]
I'm ok with either, whichever you think looks best and is clearest.

**Comment by rafaqz** [comment]
Shortening the index display to 4 elements would be great. It was annoying me today scrolling across in the Atom/Juno popup to check the `end`/`end-1` values of the dim.
