### ISSUE TITLE
Package broken for v1.6

### ISSUE THREAD

**Issue by sethaxen** [rafaqz/DimensionalData.jl#547]
#541 (included in v0.25.1) broke DimensionalData for Julia v1.6, since it assumes that `CHOLMOD` has been defined. #542 (included in v0.25.2) fixed this but simultaneously dropped support for Julia v1.6 and v1.7, which leaves the most recent version of DimensionalData that supports v1.6 broken.

Why was support for the LTS dropped?

**Comment by rafaqz** [comment]
Damn, failed the rushed fix. It should still support 1.6 that was the plan. 

(Basically my dev time is squeezed accross way too many packages and mistakes are creeping in, that was not at all intentional)

Actually testing on 1.6 is harder.

**Comment by rafaqz** [comment]
Probably we need review on every PR from now on, but Im not sure if anyone is commited to doing that.

**Comment by sethaxen** [comment]
That's fine, I completely understand.

I'm happy to review. I don't understand the internals enough to catch any major problems there, but I can at least check problems like this or that changes in functionality are properly tested.

**Comment by rafaqz** [comment]
Great, I'll ask for a few more reviews then. 

Probably simplifyimg thd internals are a prority too, there is a bunch of complexity I want to ckean up.

Anyeay, this is fixed on main
