### ISSUE TITLE
Something isn't rendering correctly in the documentation for `Base.fill`

### ISSUE THREAD

**Issue by kdheepak** [rafaqz/DimensionalData.jl#548]
https://github.com/rafaqz/DimensionalData.jl/blob/77409f54a8fe82e007e3401b18e47d758da5a3f8/src/array/array.jl#L409-L433

![image](https://github.com/rafaqz/DimensionalData.jl/assets/1813121/c10d7439-c69c-4368-9f72-50efd396bfe4)

**Comment by rafaqz** [comment]
Looks like a linebresk missing
