### ISSUE TITLE
broadcasting over dimensions, as in xarray

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#57]
In Python, the dimensions are also `xarray` just as the normal "dimensional arrays". This means that one can do normal operations on the dimensions as well, e.g. the cosine of the longitude still returns an xarray. 

Here we cant do that:
```julia
julia> x
dimension Longitude
val: [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5  …  350.5, 351.5, 352.5, 353.5, 354.5, 355.5, 356.5, 357.5, 358.5, 359.5]
grid: DimensionalData.UnknownGrid()
metadata: nothing
type: Lon{Array{Float64,1},DimensionalData.UnknownGrid,Nothing}

julia> cos.(x)
ERROR: MethodError: Cannot `convert` an object of type Float64 to an object of type Array{Float64,1}
Closest candidates are:
  convert(::Type{Array{T,N}}, ::FillArrays.Zeros{V,N,Axes} where Axes) where {T, V, N} at C:\Users\datse\.julia\packages\FillArrays\Aj0C4\src\FillArrays.jl:339
  convert(::Type{Array{T,N}}, ::FillArrays.Ones{V,N,Axes} where Axes) where {T, V, N} at C:\Users\datse\.julia\packages\FillArrays\Aj0C4\src\FillArrays.jl:339
  convert(::Type{Array{T,N}}, ::FillArrays.AbstractFill{V,N,Axes} where Axes) where {T, V, N} at C:\Users\datse\.julia\packages\FillArrays\Aj0C4\src\FillArrays.jl:331
  ...
Stacktrace:
 [1] setindex!(::Array{Array{Float64,1},1}, ::Float64, ::Int64) at .\array.jl:782
 [2] broadcasted(::Function, ::Lon{Array{Float64,1},DimensionalData.UnknownGrid,Nothing}) at .\abstractarray.jl:725      
 [3] top-level scope at none:0

julia> eltype(x)
Array{Float64,1}
```
I think the culptrit is that `eltype(x)` returns the vector instead of teh element type of the vector.

Shouldn't broadcasting over dimensions create a `DimensionalArray` with one dimension (the dimension we broadcast over) and as data the broadcast result?

I've solved #41 but I now realize it is super clunky to use, as I have to transform all the dimensions of my fields into `DimensionalArray`s...

**Comment by Datseris** [comment]
At the moment I am doing a workaround:
```
    d = dims(ds)
    return ntuple(i -> DimensionalArray(val(d[i]), (d[i],)), length(d))
```

**Comment by rafaqz** [comment]
Oh right eltype should return the element of the vector. With the caveat that the dim can hold a anything else as well, in which case the type should be the eltype. 

It's a bit awkward using dims for both holding the index and and indexing, but I like the symetry.

**Comment by rafaqz** [comment]
Also see #2

**Comment by Datseris** [comment]
Until this is fixed, here is a simple workaround that makes all dimensions DImensionalArrays:
```julia
function dims_as_dimarrays(A::AbDimArray{T, N}) where {T, N}
    d = dims(A)
    return ntuple(i -> DimensionalArray(d[i].val, (d[i],)))
end
```

**Comment by rafaqz** [comment]
I'm not sure selecting the dimensions should return a DimensionalArray... Shouldn't it just return the same dimension but subsetted? We could move some of the `slicedims` behaviour to the dimension getindex and have it rebuild itself. Then doing that manually would also work, so:

```julia
X(10:10:100)[1:5] == X(10:10:50)
```
??

Then we can make broadcast etc work on dims as well... so 
```julia
X(10:10:100) .* 2 == X(20:20:200)
```

**Comment by Datseris** [comment]
I am a bit confused by this comment. Indexing into dimensions is a different story that what the original post here is discussing.

What is discussed here is doing numerical operation on a full dimension, but not for indexing purposes... For example `cos.(lat)` to return something that has the cosine of each latitude and the information about the original latitudes. The purpose is to be able to use this result in e.g. `dimwise` and other further numeric operations.

```
X(10:10:100) .* 2 == X(20:20:200)
```
Sure this makes sense here with the trivial `.*2`, but what about `cos.(X(...))` ?

In general doing this:
```julia
f.( X(...) ) = X( f.(...) )
```
is totally fine with me, provided that the result can be used in performing numeric operations with other `DimensionalArray`s.

**Comment by rafaqz** [comment]
> to return something that has the cosine of each latitude and the information about the original latitudes

Ok I think I understand what your use-case is. And it's totally valid - but maybe not something that can be a default behaviour with broadcast, as broadcast usually tries to return the same type of object whenever possible.

But we could work out a syntax that makes it easy to do that kind of transformation: 

```
DimensionalArray(f, dim::AbDim) = DimensionalArray(f.(dim), dim, (), name(dim))
```
?

**Comment by Datseris** [comment]
Yes I think this is a fair compromise and I'll put this in the docs PR once you've gone through it once.
