### ISSUE TITLE
Design of label field for DimArray

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#58]
Cf. #53 . I was about to do the label field (I don't know what is better: label or name?), but I"ve realized that we should discuss first whether this field should propagate.

Initially my plan was to simply print the DimArray as `DimensionalArray, labelled $(label) with dim....`. But my concern is, should the `label` field be propagated after operations? At first I though "sure". And my plan was to simply edit `rebuild` to propagate the field.

The issue of course is that one can just add two DimArrays with different labels. Then there it doesn't make sense to propagate either of the labels...

So, should we just keep it simple and not propagate the name at any operation? Or are there some specific operations that it makes sense to propagate the field?

**Comment by rafaqz** [comment]
The field is `name`, `label` is a composite for display... But I've been thinking about this too. It is odd when use `zero()` or something on an an GeoArray and it keeps the name, and you have to do `rebuild(a; name="x")` or `GeoArray(A; name="x")` or `@set a.name = "x"` with Setfield.jl.

Maybe we could and pass an empty name to a `rebuild` in `similar()`.

**Comment by Datseris** [comment]
> Maybe we could and pass an empty name to a `rebuild` in `similar()`.

Sorry, I didn't understand this. Can you explain it a bit more? In general you also think that inheriting name does not make sense for most methods, right?

**Comment by rafaqz** [comment]
Most of the time I want to inherit the name. After `getindex`, `view` etc the data is still the same thing. Like "surface_temp".

Even after mean/median whatever the content is still from the same source and the name still has a similar meaning. 

But after `zero`, `one` or `similar` there is nothing but the type.
