### ISSUE TITLE
Broadcasting over a `DimArray` drops the name field

### ISSUE THREAD

**Issue by JoshuaBillson** [rafaqz/DimensionalData.jl#580]
### Problem:

I've found that broadcasting over a `DimArray` causes the `name` field to be set to `Symbol("")`

I find this behaviour to be quite unexpected. Moreover, it's difficult to feed a broadcasted array into a table, since the column names depend on the array name.

### Minimal Example:
```julia
julia> array = DimArray(zeros(2, 2), (:X, :Y), name=:Band_1)
2×2 DimArray{Float64,2} Band_1 with dimensions: Dim{:X}, Dim{:Y}
 0.0  0.0
 0.0  0.0

julia> array.name
:Band_1

julia> (array .* 1.0).name
Symbol("")
```

**Comment by lazarusA** [comment]
You should rename it to the previous name, plus the operation applied.

**Comment by JoshuaBillson** [comment]
> You should rename it to the previous name, plus the operation applied.

The use-case that prompted this issue was converting digital numbers into reflectance for satellite imagery. For example, calculating the surface-reflectance for Sentinel 2 imagery is done as follows:
```julia
sentinel .* 0.0001f0
```

In this case, if a layer has the name `:B04`, I would like it to retain this after converting it to reflectance. Otherwise, downstream code that depends on the band name will break. The current solution is to rely on `rebuild` to restore the original name, but this can be quite tedious in practice and is easy to forget about. Layer names could also get long after applying multiple operations in sequence, such as `(landsat .* 0.0000275f0) .+ -0.2f0`, which I'm assuming would include both multiplication and addition.

**Comment by rafaqz** [comment]
This is the problem, what to do in this case:
```julia
mycustomfunction.(sentinel .* 0.0001f0 .* some_other_dim_array.^2) ./ yet_another_dim_array
```
Its a broadcast just like yours, and at the level of `similar` we cant tell which is which.

**Comment by JoshuaBillson** [comment]
I suppose that one could use `modify` in such cases, which will retain the name of the desired array. You could also extract the data of all arrays whose name you don't want to retain, so that only one operand is a `DimArray`.

Perhaps we should consider that broadcasting directly over a `DimArray` is a bad idea? As you pointed out, it can be difficult to determine the identity of the output array based solely on the input. It might be better to provide a method that requires users to specify the name of the output.

**Comment by rafaqz** [comment]
Broadcasting is a huge use case of `DimArray` and arrays generally in Julia. Its how everything works internally in Rasters.jl - DiskArrays.jl has lazy broadcasting over big data so we leverage this.

We could (should) allow you to specify the name in `broadcast_dims` which we own - but it doesn't have the nice syntax of base broadcasting.

This is just a hard problem.

**Comment by rafaqz** [comment]
This is partially solved now using the `@d` macro. You can just use `name=:newname` as a macro argument after the broadcast.

Its not automated, but automating this is hard. Anyway, I will close this now. A new issue may propose how to automate guessing the name generically.
