### ISSUE TITLE
[Example] Best way to dispatch on dimensions?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#59]
I have written some functions that do some statistical analysis. This analysis depends on whether the given array has dimensions `Lon, Lat` or if it has dimension `Time`, or if it has all 3. 

At the moment each function has a different name, but I am wondering, it would be really cool to be able to dispatch on dimensions. I am searching for examples to do that. I couldn't find any in this repo, but I found https://github.com/rafaqz/GeoData.jl/blob/master/src/plotrecipes.jl#L29 which does

`function f(A::GeoArray{T,3,<:Tuple{<:Lat,<:Lon,D}}) where {T,D}`

This is almost there, my remaining concern is that this somehow enforces the dimension ordering... Do you think there is any possible way to write dispatch so that e.g. I can do:

* dispatch on something that has 2 dimensions, one Lon, one Lat, in any order,
* dispatch on something that has 3 dimensions, one Lon, one Lat, one Time, in any order

etc.?

**Comment by rafaqz** [comment]
For spatial plotting the Lat/Lon order actually matters, and the array gets permuted if it doesn't match, then tries again.

To match any order you will need to use traits. Maybe this will work (untested):

```julia
struct HasLonLat end
haslonlat(dims) = hasdim(dims, Lon()) && hasdim(dims, Lat()) ? HasLonLat() : Nothing

somefunc(dims, arg....) = somefunc(haslonlat(dims), dims, args...)
somefunc(::HasLonLat, dims, arg....) = do your thing
somefunc(::Nothing, dims, arg....) = do something else
```

And the same for HasLonLatTime. They should compile away.

**Comment by rafaqz** [comment]
For spatial plotting the Lat/Lon order actually matters, and the array gets permuted if it doesn't match, then tries again.

To match any order you will probably need to use traits:

```julia
# Define a HasXY trait:
struct HasXY end
hasxy(dims) = hasdim(dims, X()) && hasdim(dims, Y()) ? HasXY() : nothing

no = (Y(10:30), Time(1:4))
yes = (Y(10:30), X(1:10))

julia> @inferred hasxy(no)

julia> @inferred hasxy(yes)
HasXY()

somefunc(dims, args...) = somefunc(hasxy(dims), dims, args...)
somefunc(::HasXY, dims, args...) = "do your thing"
somefunc(::Nothing, dims, args...) = "do something else"

julia> somefunc(yes)
"do your thing"

julia> somefunc(no)
"do something else"
```

**Comment by Datseris** [comment]
Oh this is a nice idea! I'll test it in my code tomorrow then! if it works fine should I put it in the docs as an "advanced example"? I can point to the plot recipe (or some other dimension-dispatch code in GeoData.jl, preferably unrelated with plotting) as well.

**Comment by rafaqz** [comment]
BTW  with #69 you can now do this on abstract dimensions `XDim` `YDim` etc. Although notice that `Ti` is actually `<: XDim` so the original example wouldn't work. Here I use `Z` instead.

```julia
# Define a HasXY trait on abstract dim types XDim and YDim
struct HasXY end
hasxy(dims) = hasdim(dims, XDim) && hasdim(dims, YDim) ? HasXY() : nothing

no = (Y(10:30), Z(1:4))
yes = (Y(10:30), X(1:10))

julia> @inferred hasxy(no)

julia> @inferred hasxy(yes)
HasXY()

somefunc(dims, args...) = somefunc(hasxy(dims), dims, args...)
somefunc(::HasXY, dims, args...) = "do your thing"
somefunc(::Nothing, dims, args...) = "do something else"

julia> somefunc(yes)
"do your thing"

julia> somefunc(no)
"do something else"
```

**Comment by Datseris** [comment]
Great.

`Ti is actually <: XDim` I didn't expect this. What is the rational behind it? I was probably expecting something like `Ti <: TimeDim`.

**Comment by rafaqz** [comment]
I though that too until I though about the practicalities of plotting, and read a few things.

Time is mostly plotted on the X dimension because it always has to be the independent variable, nothing else affects it.

In 3d contexts you may want to do something different but we can handle that too by just dispatching on `Ti`, or making `TimeDim <: XDim` in between.

**Comment by Datseris** [comment]
Yeah, `TimeDim <: XDim ` seems like a brilliant idea!

**Comment by Datseris** [comment]
I am confused @rafaqz with your recent administrative decisions. You just closed 3 issues that were asking for documenting things, but none of these things were documented. Why did you close these issues?
