### ISSUE TITLE
Failing on nightly because uses private methods from Base

### ISSUE THREAD

**Issue by odow** [rafaqz/DimensionalData.jl#664]
x-ref https://github.com/jump-dev/JuMP.jl/pull/3707

https://github.com/rafaqz/DimensionalData.jl/blob/55e8ecf6fd91249caa76af5697eeb66d9f8a40d0/src/Lookups/beginend.jl#L42-L45

**Comment by rafaqz** [comment]
Its failing on nightly for multiple other reasons too if we fix that, and theyre not DD related. 

But I will fix that use if internals.
