### ISSUE TITLE
stable docs link is broken

### ISSUE THREAD

**Issue by markmbaum** [rafaqz/DimensionalData.jl#668]
this link to the "stable" version of the docs is broken: https://rafaqz.github.io/DimensionalData.jl/stable/

the "dev" link is working

<img width="975" alt="Screenshot 2024-03-12 at 1 54 02 PM" src="https://github.com/rafaqz/DimensionalData.jl/assets/18745581/4cfc9d58-02de-406d-bfcd-84bd9e31059a">

**Comment by markmbaum** [comment]
does not appear to be working

**Comment by rafaqz** [comment]
He means master of the documentation package. When thats registered we will push a fix here.

**Comment by jonathanfischer97** [comment]
The link is still broken FYI

**Comment by asinghvi17** [comment]
Someone just has to run the documentation job on that tag again.

**Comment by rafaqz** [comment]
I don't think so @asinghvi17 bumped version have not fixed it

**Comment by asinghvi17** [comment]
Oh, I forgot that DD had the extra hydration error...

**Comment by rafaqz** [comment]
It's a pretty bad look right now 😭

**Comment by spaette** [comment]
What about a redirect from `stable` to `v0.27.3`?

**Comment by rafaqz** [comment]
If you know how to do that go for it

**Comment by spaette** [comment]
Possibly a solution would be obtainable by determining how the below is accomplished.

_cf_: `https://github.com/LuxDL/DocumenterVitepress.jl`

**About**

`https://luxdl.github.io/DocumenterVitepress.jl/`

which redirects to

`https://luxdl.github.io/DocumenterVitepress.jl/v0.1.1/`

**Releases**

Releases `20`
**v0.1.1** <kbd>Latest</kbd>
last month

> [their] "dev" link is [also] working

`https://luxdl.github.io/DocumenterVitepress.jl/dev/`

**Comment by spaette** [comment]
when this is resolved you might want to modify/update README.md

this of course is optional though the current link redirects to the latter

```diff
- [See the docs for more details](https://rafaqz.github.io/DimensionalData.jl/)
+ [See the docs for more details](https://rafaqz.github.io/DimensionalData.jl/stable/)
```

this one is currently opening as a 404 without any page header/footer

```diff
- listed at the [API](https://rafaqz.github.io/DimensionalData.jl/reference) page.
+ listed at the [API](https://rafaqz.github.io/DimensionalData.jl/stable/api/reference) page.
```

**Comment by felixcremer** [comment]
This is fixed.
