### ISSUE TITLE
Improvements to docstrings

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/DimensionalData.jl#673]
I am currently reading through the docstrings and will capture confusions and possible improvements here. Feel free to ignore for now.

**Comment by felixcremer** [comment]
Label keyword in Bins not documented

**Comment by felixcremer** [comment]
Label describtion in CyclicBins should be generic and not mentio months

**Comment by felixcremer** [comment]
Typos in DimStack docstring amd maching

**Comment by felixcremer** [comment]
DimStackInterface should mention AbstractDimStack instead of Abstractdimarray

**Comment by felixcremer** [comment]
DimTable example should show DimTable

**Comment by felixcremer** [comment]
Dimensions docstring could mention exports and most common use cases.

**Comment by felixcremer** [comment]
Clarify differences betwen DimPoints and DimIndices and DimKeys

**Comment by felixcremer** [comment]
Clarify differences betwen DimPoints and DimIndices and DimKeys

**Comment by felixcremer** [comment]
Evne in LookupArrays docstring also mention exports

**Comment by felixcremer** [comment]
Does Near give a warning when out of bounds?

**Comment by rafaqz** [comment]
Near gets the nearsest however far that is, so no.

**Comment by felixcremer** [comment]
Should result in DimSelectors example be two dim not three dim?
