### ISSUE TITLE
Typo in function name

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/DimensionalData.jl#680]
In this line  https://github.com/rafaqz/DimensionalData.jl/blob/main/src/array/broadcast.jl#L88 I suspect it should be _firstdimarray.

**Comment by rafaqz** [comment]
PR?

**Comment by felixcremer** [comment]
Yes, as soon as I am back on my computer. Do you have an idea how to test it?

**Comment by felixcremer** [comment]
Fixed in #681
