### ISSUE TITLE
`using DimensionalData.Lookups` in docs does not work

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/DimensionalData.jl#699]
In the docs (https://rafaqz.github.io/DimensionalData.jl/dev/get_info) there is a `using DimensionalData.Lookups` but this is no longer valid. Does this need to be updated to `using DimensionalData.LookupArrays`?

**Comment by alex-s-gardner** [comment]
#700

**Comment by felixcremer** [comment]
On what version are you? The change to Lookups happened recently in #655.

**Comment by rafaqz** [comment]
Its the other way around! It used to be `LookupArrays`, and now its `Lookups` but `LookupArrays` will still work.

**Comment by alex-s-gardner** [comment]
was indeed using older version... I've now updated
