### ISSUE TITLE
Error when trying to construct one-dimentional Array/vector

### ISSUE THREAD

**Issue by alecloudenback** [rafaqz/DimensionalData.jl#70]
This works:

```julia
A = DimensionalArray(rand(10,10), (DimensionalData.Y(1:10),DimensionalData.X(11:20)))
```

But seems to not allow a one dimensional array (vector)? This does not work:

```julia
A = DimensionalArray(rand(10), DimensionalData.X(1:10))
```

Is there a different way to construct a one-dimensional array?

**Comment by rafaqz** [comment]
Dims had to be a tuple, `(X(), )`

But this works on master as of yesterday, and allows the above syntax. It should be registered soon.

Also on master, if your range matches the array axis, you can just do:

```julia
A = DimensionalArray(rand(10), X)
```
