### ISSUE TITLE
[Dev Question] What is the purpose/use of referenced dimensions?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/DimensionalData.jl#72]
Hi,

this is something I haven't understood yet, what's the reason of keeping some dimensions as `refdims`?

This is a bit unintuitive:
```
julia> At = timeaverage(A, 1:maxyear)
DimensionalArray with dimensions:
 Longitude (type Lon): Float32[0.5, 1.5, …, 358.5, 359.5]
 Latitude (type Lat): Float32[-89.5, -88.5, …, 88.5, 89.5]
and referenced dimensions:
 Time: 2000-03-15T00:00:00
```
it is odd for me to see that this time dimension has a single timepoint as its value (the first one). The resulting array comes from averaging over time, so no timepoint makes sense to be printed. If any it would be the `mean`, but e.g. for time data this doesn't make much sense.

**Comment by rafaqz** [comment]
Mostly for plot labels. And yes that is not the intended behaviour, just the best we could do when that was written. Now we have bounds working we can change the text to the interval of the refdim instead of just the point position. I just havent done that yet.

We can also use `cat` to join arrays along refdims, rebuilding the index.

**Comment by Datseris** [comment]
> We can also use cat to join arrays along `refdims`, rebuilding the index.

Ah, had no idea about that, we should put it in the docs.

**Comment by rafaqz** [comment]
I havent written it yet, but theres an issue for it

**Comment by rafaqz** [comment]
In your example, we can print the size of the step after the value.

```julia
Time: 2000-03-15T00:00:00, for 1 month
```

Or the bounds:

```julia
Time: 2000-03-15T00:00:00 to 2000-04-15T00:00:00
```

**Comment by Datseris** [comment]
I think the bounds are the most reasonable thing to print then. Or, we don't print values at all. Is it necessary to print the values of the referenced dimensions?

**Comment by rafaqz** [comment]
Its not really necessary to print but I do find it udeful sometimes. We could leave it out when empty.  We can also make it handle passed in `nothing` so you can turn off using it at all and get a very small performance gain. But it's good on a plot.

**Comment by rafaqz** [comment]
FYI: https://github.com/rafaqz/GeoData.jl/issues/21

**Comment by Datseris** [comment]
Seems that for this it is also the best solution to state the span of the referenced dimension.

**Comment by Datseris** [comment]
So... why was this closed? Referenced dims and their purpose is not yet documented https://rafaqz.github.io/DimensionalData.jl/dev/course/#Referenced-dimensions-1  and also the issue described here (that the referenced dimensions actually display a single value, which doesn't make sense) is not solved as far as I can tell.
