### ISSUE TITLE
Displaying one-dimensional `DimArray` does not quite work in Pluto

### ISSUE THREAD

**Issue by haakon-e** [rafaqz/DimensionalData.jl#725]
If this is issue should be directed to the Pluto repo, please let me know...

Printing `DimArray`s works nicely in (VSCode) terminal window:
![image](https://github.com/rafaqz/DimensionalData.jl/assets/45243236/1f8095dd-beef-4430-a943-0f2a9a4e0aff)

but in Pluto, it only works for `DimArray`s with multiple dimensions:
<img width="730" alt="image" src="https://github.com/rafaqz/DimensionalData.jl/assets/45243236/04db464d-826e-4075-819f-efbddad97793">

---------

<details> <summary> versioninfo </summary>

```julia
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 128 × AMD EPYC 9554 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 128 virtual cores)
Environment:
  JULIA_MPI_HAS_CUDA = true
  JULIA_CPU_TARGET = generic;broadwell;skylake-avx512;icelake-server;cascadelake;znver3
  JULIA_CUDA_MEMORY_POOL = none
  JULIA_LOAD_PATH = :/groups/esm/modules/julia-preferences/_2024_02_20
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_NUM_THREADS = 1

pkg> st 
  [...]
  [c3e4b0f8] Pluto v0.19.42
  [0703355e] DimensionalData v0.27.3
```

**Comment by rafaqz** [comment]
No idea... @fonsp ?

**Comment by asinghvi17** [comment]
Potentially related to https://github.com/JuliaGeo/Shapefile.jl/issues/50

**Comment by rafaqz** [comment]
@haakon-e what happens with a regular `Vector` ?

**Comment by haakon-e** [comment]
@rafaqz Like this?
<img width="316" alt="image" src="https://github.com/rafaqz/DimensionalData.jl/assets/45243236/ee62f304-d77f-40da-aa5f-a17481ab00e9">

**Comment by haakon-e** [comment]
I guess it's maybe similar, in the sense that a `(n x 1)` matrix will show the way you expect:
<img width="232" alt="image" src="https://github.com/rafaqz/DimensionalData.jl/assets/45243236/49de2dc5-818f-4d0c-a58e-c9b3ffab2587">

while a vector (as above) is "compressed" into a horizontal view.

vs terminal:
![image](https://github.com/rafaqz/DimensionalData.jl/assets/45243236/20fd5b7c-780e-4274-a26a-e0a87690c999)

**Comment by rafaqz** [comment]
Ok, well that seems to be a Pluto.jl decision. I'm not sure there is much we can do about it. You could make an issue over there and see if they know any solutions?

**Comment by haakon-e** [comment]
Thanks.

It seems others have had similar(?) issues that was worked around for display, e.g. https://github.com/TuringLang/MCMCChains.jl/pull/279 / https://github.com/fonsp/Pluto.jl/issues/868

**Comment by haakon-e** [comment]
Asked question here: https://github.com/fonsp/Pluto.jl/discussions/2936
