### ISSUE TITLE
Add CodeCov upload token to fix codecov

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/DimensionalData.jl#738]
Currently the test coverage info at codecov is outdated by two months. 
This is because we are not using the codecov upload token.
Could you please add the codecov upload token to the repo as described here:

https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

**Comment by rafaqz** [comment]
Ok added. This is going to be extremely painful to do for every single package

**Comment by felixcremer** [comment]
This is still not uploading correctly. My latest PR still had the upload problems but I have no idea, why this is still happening.

**Comment by felixcremer** [comment]
Ahh, I just read a bit about that on the Julia slack and the problem seems to be, that forks don't have access to the Secrets, so it can't upload the data with the token, when the PR comes from outside of your github repository. 
So it seems, as if we would have to live with not having the current CodeCov info up there.

**Comment by rafaqz** [comment]
Why did they do this 😭
