### ISSUE TITLE
Invalid assignment to DimArray indexed by DimSelectors

### ISSUE THREAD

**Issue by ggebbie** [rafaqz/DimensionalData.jl#758]
Great package! I use it a lot.

Here's what I'd like to accomplish (assignment/update to a DimSelectors index):
```julia
A = rand(X(1.0:0.2:2.0), Y(10:2:20))
 B = rand(X(1.0:0.2:1.6), Y(10:2:20))

 A[DimSelectors(B)] # all ok with output to screen
 A[DimSelectors(B)] += B # long error including "Use stardard indices, `Selector`s, or `Val` for compile-time `At`."
```

I didn't expect my naive formulation to work, but I haven't found a workaround yet. Closed issue  #683 seems close. I am guessing that `rebuild` may be one way to accomplish my goal.

**Comment by rafaqz** [comment]
Thanks, seems there are a few bugs there, will fix.

**Comment by ggebbie** [comment]
I confirm that the bug fix works for me. Thanks a ton!  This bug fix will help me showcase `DimensionalData.jl` in a computational notebook that will accompany a manuscript submission to _Journal of Advances in Modeling Earth Systems_ .

**Comment by rafaqz** [comment]
Amazing, post the paper when its out :)
