### ISSUE TITLE
missing function in plot recipe

### ISSUE THREAD

**Issue by xzackli** [rafaqz/DimensionalData.jl#773]
`_lookup_to_axis` doesn't appear to be defined anywhere, but is used in the Makie recipe.

https://github.com/rafaqz/DimensionalData.jl/blob/d10d0fc6bd2021487762d93eb711fb8084f7f567/ext/DimensionalDataMakie.jl#L384

**Comment by rafaqz** [comment]
Ahh right I just changed it, we mustn't test plots going through that dispatch.

Do you have an example I can put in the tests?
