### ISSUE TITLE
EmptyDims

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#79]
What the use case for `EmptyDims`? Should it be the added dimension whenever a DimensionalArray get's an unnamed dim added (e.g. `a[:, :]` where a is 1d)?

Also, should EmptyDims always have size one? That could solve the `dimvec' * dimvec` issue by defining something like:

```julia
*(DimArray{<:Any, 2, Tuple{EmptyDim, <:Any}}, DimArray{<:Any, 1})
```

**Comment by rafaqz** [comment]
I'm not totally clear on that yet, that's why it has such vague name... I was thinking we could define `EmptyDimLengthOne` or something?

**Comment by ivirshup** [comment]
Is the dimension given from an adjoint or a transpose inherently different than (though this does currently error):

```julia
da = DimensionalArray(collect(1:5), Y)
vcat(da', da')
```

I guess I'm wondering: is there a difference between an "Empty" dimension and a dimension that hasn't been given a name?

**Comment by rafaqz** [comment]
Yes that question isn't really resolved yet... You still have to pass some dimension to `cat` currently, but we should allow it to work without one, and just insert the `EmptyDim`.

So: can you think of any reasons `EmptyDim` can't work for both cases? We can also rename it if there is a better name.

**Comment by ivirshup** [comment]
I was mainly wondering if you had anything specific in mind for `EmptyDim`s. 

I think there would could be value in having "anonymous" dimensions, which allows partially labelled arrays. I'm not sure if this breaks the data model though, and I'm not sure if there's value in having a special type for certain 1 element cases.

**Comment by rafaqz** [comment]
I had no plans beyond what it does currently, and I knew this conversation would have to happen at some point. It's basically a placeholder for us to flesh out.

**Comment by ivirshup** [comment]
I'm currently thinking there should be a unnamed dim type which only allows basic indexing, and is always the size of the underlying array axis. Something like `AnonymousDimension`.

**Comment by rafaqz** [comment]
I think `AnonymousDim` could be clearer than `EmptyDim`.

**Comment by ivirshup** [comment]
Yeah, but it could use a shorter name.

**Comment by rafaqz** [comment]
`AnonDim`
