### ISSUE TITLE
Datasets?

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#80]
Would you be interested in supporting something like the `xarray.Dataset` in this package (or in a related one)? Namely, a collection of dimensional arrays with shared indices which you can do joint operations (like indexing and split-apply-combine) on?

One of the main issues with this would be the lack of type stability (the object is close to `Dict{String, DimArray{Any...}}`), though operations which require dealing with this should be pretty high level. I'm not up to date on the state of performance in packages which face similar issues , i.e. `DataFrames.jl`. I imagine those packages probably have relevant experience.

**Comment by rafaqz** [comment]
See [GeoStack](https://github.com/rafaqz/GeoData.jl/blob/master/src/stack.jl) in GeoData.jl. It uses `NamedTuple` instead of Dict for type stability and performance. This package uses a functional style specifically so we can avoid using `Dict` and things like it.

The stack is assumed to have _some_ shared indices, but currently it actually doesn't because the arrays are loaded lazily, not at the point of construction of the GeoStack, so we don't even know what the indices are.

They also can't have completely shared dimensions in practise, as they may share only a subset of dimensions (Lat, Lon in GeoData) but have additional dimensions like Time for some layers.

We could move some of it over here if has broader uses than spatial data.

**Comment by ivirshup** [comment]
I'm interested in the that use of named tuple. How often do you mutate or create `GeoStack` instances? For my use case, the object would be modified pretty frequently, which would cause quite a lot of compilation.

> sometimes the arrays are loaded lazily, not at the point of construction of the GeoStack, so we don't even know what the indices are.

Is this for working with NetCDF data? I'm curious to know why you wouldn't know the indices yet, my understanding was that should all be in the metadata.

> They also can't have completely shared dimensions in practise, as they may share only a subset of dimensions (Lat, Lon in GeoData) but have additional dimensions like Time for some layers.

Just to clarify, I was thinking a dataset would have dimensions, and elements of the dataset would have some permutation of these dimensions as their axes. Does that fit with your model?

**Comment by rafaqz** [comment]
It's very rarely changed tbh. Yes this will be about weighing up compilation time vs access time tradeoffs.

GeoStack is for working with any abstract layout of spatial data that presents the same indexing interface so modelling tools can just work with the AbstractGeoStack interface and ignore the actual layout of files and layers etc. It could be a list geotiff file paths, a hdf5 file, a netcdf file or list of paths to single layer netcdf, urls for zarr databases, etc etc. 

I think you're talking about a different data model to `GeoStack`, where dimension sharing is more strict. But I'm not sure if it's necessary to separate them.

**Comment by ivirshup** [comment]
> It's very rarely changed tbh. Yes this will be about weighing up compilation time vs access time tradeoffs.

I have a slightly different perspective on this. Access to a `Dict{String, Any}` will be faster than compilation time using a named tuple. My sense is that access will be in high-level interactive analysis code, not hot loops. I think the question is whether it's easy for users to write functions which don't "poison the well" by having an untyped value. It can be difficult to understand what the compiler is capable of, and when you need to place function barriers. There's a similar issue with the named tuple approach, where the amount of code that needs to be recompiled will vary with code structure.

> I think you're talking about a different data model to GeoStack

I think a lot of the file access would be useful, since the data I'm working with is stored in hdf5 or zarr files. I am also looking at abstracting out the on-disk format more (right now, it's basically hdf5 or zarr files with a particular structure), so I'd be interested in seeing how you've done this. I can elaborate on this and the rest of my use case if that'd be helpful, but it might be a bit long.

**Comment by rafaqz** [comment]
My use case is in simulation loops running over hundreds of files. Which shouldn't be a problem as long as I use a function barrier somewhere. 
I would be open to changing the architecture if it made more sense to use `Dict`. But I also like that you don't have to think about state.

If you look in the `sources` directory in GeoData.jl you'll find files implementing the interface for different data sources, that mostly define some `AbstractGeoStack`. In my main use case currently (GrowthMaps.jl) we swap between running models over 3-hourly hdtf5 files, 3-hourly netcdf files and tifs where each layer is a separate file. 

`GeoSeries` gives you a wrapper around `GeoArray` or `GeoStack` that gives you another outer dimension, so you can have a series of datasets in separate files along some dimension, often time.

Methods like `aggregate` in GeoData.jl can then work on the entire series (maybe hundreds of files) in one operation giving you the same in-memory stacks and arrays independent of what the source data was.

**Comment by ivirshup** [comment]
> I would be open to changing the architecture if it made more sense to use Dict. But I also like that you don't have to think about state.

What do you mean by "having to think about state"?

**Comment by rafaqz** [comment]
Only the array and dimension index have state. Which we don't really care about - that's the users business. 

Everything else is stateless so all transformations are done by some function and can take care of whatever other changes need to be made. The exception is that Metadata is in a `Dict`, which I'm still not sure about.

**Comment by rafaqz** [comment]
Thinking about your dataset case, it's actually quite different to GeoStack... you are talking about them being identical layers so all the dims metadata is held outside of the layer, in the dataset object.

In GeoStack, each layer can be whole regular GeoArrays with everything attached - as the dims don't necessarily match it's the easiest way. It mean there is less state in your case - the Dict is are just a list of regular Array (or similar).

You could implement that here if you need it, it should be pretty simple. Just needs a name.
