### ISSUE TITLE
Lookup conversion helper functions

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/DimensionalData.jl#807]
I find myself needing the utility of these three lookup helper functions contained in GeoMakie and I'm wondering if it would make sense to bring these over to DD:

https://github.com/rafaqz/DimensionalData.jl/blob/79b2f879023146943ba13e5c0d526d648b33a99b/ext/DimensionalDataMakie.jl#L631-L660

**Comment by asinghvi17** [comment]
I would say that `edgevector` on at least Regular and Irregular lookups would be valuable for histograms etc?

**Comment by rafaqz** [comment]
Maybe, I'm not sure it's worth the extra function when we have `intervalbounds` already
