### ISSUE TITLE
[FR] AlgebraOfGraphics.jl support

### ISSUE THREAD

**Issue by kapple19** [rafaqz/DimensionalData.jl#821]
For a `v::DimArray`, it would be nice for `AlgebraOfGraphics.data(v)` to work.
`AlgebraOfGraphics.mapping(X, Y)` as well, of course,
and for arbitrary dimension names, e.g. `AlgebraOfGraphics.mapping(:a, :b)`.

**Comment by rafaqz** [comment]
Sounds good.

Personally I use raw Makie.jl so I'm not really across what AOG adds! We should make basic Makie recipes do as much as possible, but if there are extra methods we can add to help AOG I'm happy for someone to write an extension.

Can you maybe explain a bit more what these methods do now and what you would like them to do with a DimArray?

**Comment by asinghvi17** [comment]
Does mapping with symbols not work already?

**Comment by kapple19** [comment]
> Can you maybe explain a bit more what these methods do now and what you would like them to do with a DimArray?

> Does mapping with symbols not work already?

Here's some examples:

```
using DimensionalData
using CairoMakie, AlgebraOfGraphics

P = Dim{:p}

v = DimArray(
    rand(21, 5, 4),
    (X, Y, P);
    name = :RandomData
)

dat = data(v)
scat = vis * visual(Scatter)
line = vis * visual(Series)
heat = dat * visual(Heatmap)

scat * mapping(:x, Y, color = :p) |> draw
scat * mapping(X, Y, color = P) |> draw
scat * mapping(X, P, color = Y) |> draw
line * mapping(X, Y, color = P) |> draw
scat * mapping(X, Y, layout = P) |> draw
scat * mapping(X, Y, row = P) |> draw
scat * mapping(X, Y, col = P) |> draw
heat * mapping(X, Y, layout = P) |> draw
heat * mapping(P, X, layout = Y) |> draw
```

I'll update this post with how the above turns out, just waiting for Makie to compile 😅.

**Comment by asinghvi17** [comment]
It would have to be the exact symbol, so `:X`

**Comment by kapple19** [comment]
> It would have to be the exact symbol, so `:X`

Oh, you're right 😅.

However,

```
scat * mapping(:X, :Y, color = :p) |> draw
```

![image](https://github.com/user-attachments/assets/b45b1797-a3e1-4c3c-a370-bf58a9091d0e)

**Comment by rafaqz** [comment]
> DimArrays aren't long-formatted tabular data

They actually are! Tables.jl is implemented. For `DimStack` too of course. But using `DimTable(x)` may help, in case there is `AbstractArray` specific dispatch in AOG that skip around the tabular part.

It will of course grab the dimensions values, as that's what's in the X and Y columns. If you want the data, name the DimArray and use that name in AOG . That's the data

**Comment by kapple19** [comment]
AHH! I see.

```
scat * mapping(:X, :RandomData, color = :Y) |> draw
```

![image](https://github.com/user-attachments/assets/eafb9098-83fd-4304-ab55-bd6b30661940)

**Comment by rafaqz** [comment]
This is awesome we should add a tutorial to the docs

**Comment by kapple19** [comment]
Do you know what's going wrong here?

![image](https://github.com/user-attachments/assets/95bb1b19-dcd0-476b-8b0e-591463aef8f8)

**Comment by asinghvi17** [comment]
Yes, there is no `row` kwarg to heatmap...where did you get that from?

**Comment by rafaqz** [comment]
@kapple19 by adding docs I mean if you end up with a nice workflow and some example you can put them here in an AlgebraOfGraphics section under the Makie section:
https://github.com/rafaqz/DimensionalData.jl/blob/main/docs/src/plots.md

**Comment by kapple19** [comment]
> Yes, there is no `row` kwarg to heatmap...where did you get that from?

AH, good point. That reminded me to use `nonnumeric`.

```
heat * mapping(:X, :RandomData, :p, layout = :Y => nonnumeric) |> draw
```

![image](https://github.com/user-attachments/assets/a24c7086-c3ff-493e-9014-72fa1219ac1e)

Okay, I'm happy for this to be closed, unless we want to keep this open to scope passing `Dim` objects to `AlgebraOfGraphics.mapping`.

I'm happy to contribute to the documentation soon as well.

**Comment by kapple19** [comment]
I'm also curious as to if/how AlgebraOfGraphics could work with nested `DimArray`s. But it's 2 AM where I am and I need to sleep now. 😅

**Comment by rafaqz** [comment]
No stress at all with the docs, I just linked so it has the minimum possible friction if/when you have time and inclination

**Comment by asinghvi17** [comment]
![meme](https://i.imgflip.com/2a9xgs.jpg)

**Comment by jkrumbiegel** [comment]
The `row` dictionary error above is when you pass a numeric column to one of the mappings that can only deal with categorical data (you can only facet rows using categorical data). It's a bad error for sure, I'll make an issue in AoG

**Comment by asinghvi17** [comment]
There's also a pretty simple patch that allows AoG to select using dimension types (like `X`).  I'll push a PR in a few.

**Comment by kapple19** [comment]
Fricken awesome. Thanks everyone. 😁
