### ISSUE TITLE
improved RollingFunctions.jl integration

### ISSUE THREAD

**Issue by simeonschaub** [rafaqz/DimensionalData.jl#851]
RollingFunctions.jl already works with AbstractDimArrays, but unfortunately the dimension is lost in the process. Python's xarray has a method [`rolling`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.rolling.html) which keeps the original dimensions of the array and even has a particularly useful `center` argument to specify that the labels should be set at the center of the window.
It also supports a `dim` argument which RollingFunctions.jl doesn't have AFAIK, but I'm thinking that this might not be necessary and with #850, one could just use `eachslice` for this.
Would it be reasonable to add an extension here supporting such a use case?

**Comment by lazarusA** [comment]
mmm... I thought this was covered by https://rafaqz.github.io/DimensionalData.jl/stable/groupby#binning and https://rafaqz.github.io/DimensionalData.jl/stable/groupby#Select-by-Dimension, maybe we could show it more, if indeed is the same.

**Comment by simeonschaub** [comment]
IIUC binning is not the same as applying a rolling function though, since bins are disjoint whereas the point of rolling functions is that there are sliding windows that overlap.

**Comment by lazarusA** [comment]
well, for moving windows (xarray-like) we have [this](https://juliadatacubes.github.io/YAXArrays.jl/dev/api.html#YAXArrays.DAT.MovingWindow) in yaxarrays, but is [not documented](https://github.com/JuliaDataCubes/YAXArrays.jl/issues/459) yet.

**Comment by rafaqz** [comment]
I was thinking we needed an extension, but actually Stencils.jl doesn't and still returns a DimArray;

https://github.com/rafaqz/Stencils.jl/blob/main/test%2Farray.jl#L170-L172

So this is a Rolling function.jl problem. To fix it generically for all inputs, they probably need to use `similar` to generate the output array, and then write into it.

**Comment by simeonschaub** [comment]
I ended up creating my own package in https://github.com/simeonschaub/RollingWindowArrays.jl for rolling window operations since I wasn't really satisfied with RollingFunctions.jl because its implementation is quite complex and hard to extend. I think this issue can probably be closed.
