### ISSUE TITLE
Document plot recipes

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#91]
Also put demo plots in the readme/module docs.

Adds some bling.

**Comment by tomchor** [comment]
I saw this issue is still open. I'm really interested in this package as a way to visualize my results more easily. Are there any example scripts anywhere?

**Comment by rafaqz** [comment]
You don't really need examples to use it... it's just the functions from Plots.jl and StatsPlots.jl.

Like `plot(dimarray)`, `heatmap(dimarray)`, `histogram(dimarray)`
 etc. They just work and should put labels in the right places snd permute dimensions correctly.

But examples would help showcase it, for sure.

**Comment by rafaqz** [comment]
There are a bunch of examples now in the docs, including for AlgebraOfGraphics
