### ISSUE TITLE
Checking whether dimension is ordered currently requires values to have order

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#93]
Example:

```julia
using DimensionalData

struct Foo
    x
end

DimensionalArray(ones(2), X([Foo(1), Foo(2)]))
```

<details>
<summary> Traceback </summary>

```julia
ERROR: MethodError: no method matching isless(::Foo, ::Foo)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:87
  isless(::Any, ::Missing) at missing.jl:88
Stacktrace:
 [1] <(::Foo, ::Foo) at ./operators.jl:268
 [2] <=(::Foo, ::Foo) at ./operators.jl:317
 [3] indexorder(::Array{Foo,1}) at /Users/isaac/github/DimensionalData.jl/src/primitives.jl:237
 [4] orderof(::Array{Foo,1}) at /Users/isaac/github/DimensionalData.jl/src/primitives.jl:233
 [5] identify(::UnknownGrid, ::Array{Foo,1}) at /Users/isaac/github/DimensionalData.jl/src/grid.jl:372
 [6] formatdims(::Array{Foo,1}, ::Base.OneTo{Int64}, ::X{Array{Foo,1},UnknownGrid,Nothing}) at /Users/isaac/github/DimensionalData.jl/src/primitives.jl:213
 [7] formatdims(::Tuple{Base.OneTo{Int64}}, ::Tuple{X{Array{Foo,1},UnknownGrid,Nothing}}) at ./tuple.jl:178
 [8] formatdims(::Array{Float64,1}, ::Tuple{X{Array{Foo,1},UnknownGrid,Nothing}}) at /Users/isaac/github/DimensionalData.jl/src/primitives.jl:208
 [9] formatdims(::Array{Float64,1}, ::X{Array{Foo,1},UnknownGrid,Nothing}) at /Users/isaac/github/DimensionalData.jl/src/primitives.jl:202
 [10] #DimensionalArray#12(::Tuple{}, ::Type{DimensionalArray}, ::Array{Float64,1}, ::X{Array{Foo,1},UnknownGrid,Nothing}, ::String) at /Users/isaac/github/DimensionalData.jl/src/array.jl:109
 [11] DimensionalArray(::Array{Float64,1}, ::X{Array{Foo,1},UnknownGrid,Nothing}, ::String) at /Users/isaac/github/DimensionalData.jl/src/array.jl:109 (repeats 2 times)
 [12] top-level scope at REPL[5]:1
```

</details>

Currently, the check to see if a dimension is sorted requires that  the values of the dimension have an ordering. This came up when I was doing a grouped reduction where the group labels were stored in a `CategoricalArray`. Since CategoricalStrings are not defined to have order, creating a dimensional array failed with the above error.

**Comment by rafaqz** [comment]
Yeah its a crude approach currently. We need to only use that on elements with an `isless` method. Otherwise they're `Unordered`

**Comment by ivirshup** [comment]
Is there a good way to check if an type has a method? There's `hasmethod(<, eltype(dim), eltype(dim))`, but it doesn't look like that will compile away.

**Comment by ivirshup** [comment]
I'm wondering if "order" should be determined by value of the elements, rather than the type of the container. If I'm providing string labels, there's a good chance my definition of "ordered" for the labels is not `issorted`.

The definition or `order` may also be a bit buggy at the moment:

```julia
julia> order(dims(DimensionalArray(ones(3), (X([3, 1, 2]))))[1])
Unordered{DimensionalData.Forward}(DimensionalData.Forward())

julia> order(X([3,1,2]))
Ordered{DimensionalData.Forward,DimensionalData.Forward,DimensionalData.Forward}(DimensionalData.Forward(), DimensionalData.Forward(), DimensionalData.Forward())

julia> order(dims(DimensionalArray(ones(3), (X(1:3)))[[3, 1, 2]])[1])
Ordered{DimensionalData.Forward,DimensionalData.Forward,DimensionalData.Forward}(DimensionalData.Forward(), DimensionalData.Forward(), DimensionalData.Forward())
```

**Comment by rafaqz** [comment]
"a", "b" "c" ?

But absolutely it will be buggy.  You'll find some comments around about indexing with unordered arrays needing work.

**Comment by ivirshup** [comment]
I was thinking more: `["Group1", "Group2", "Group10"]`.

In general, I think it would be good to skip the ~O(N) `issorted` check on array indices unless the user definitely wants that.

**Comment by rafaqz** [comment]
That's a good point. We probably shouldn't use `issorted` at all.

But we need to get a good balance between automatically detecting grid properties and easy ways of defining them manually. I have a local branch playing with using keyword args to define the grid properties. We could aim for a syntax where you do something like:

```julia
X(["a", "b", "c"]; order=Forward())
```

Or something.

**Comment by ivirshup** [comment]
I was wondering if properties like this could be deferred to the dimension's values.

For example, [AxisIndices](https://tokazama.github.io/AxisIndices.jl/dev/axis_intro/) maintains range objects through subsetting operations when it can. A similar idea has been brought up for [accelerated arrays](https://github.com/andyferris/AcceleratedArrays.jl/issues/4).

**Comment by rafaqz** [comment]
Can you ecpand on this? 

Dont we also maintain ranges? Its vectors that are the problem. We need to know if they are sorted for indexing speed. Eventually `At` should use `searchsortedfirst` when it can, instead of `find`.

**Comment by ivirshup** [comment]
> Can you expand on this?

Basically, there are a number of types which imply ordered value through iteration. There are subsetting operations which maintain that order. Ideally, whether a dimension is order could just be deferred to whether it's `val` is ordered. This has a potential to be type safe, and could give performance improvements since the subsetting operations can be optimized.

-----------

Oh, it looks like we do sometimes keep ranges, jut not consistently. They aren't if `At` is used:

```julia
julia> DimensionalArray(1:5, X(1:5))[At(5:-1:1)]
DimensionalArray with dimensions:
 X: Int64[5, 4, 3, 2, 1]
and data: 5-element Array{Int64,1}
[5, 4, 3, 2, 1]
```

-----------------------

Also is `At` meant to always be `findfirst`?

**Comment by rafaqz** [comment]
Yeah `At` isn't that smart yet. Otherwise we keep ranges.

The problem with relying on the order of the value is that regular `Vector` does not track its order, but often we actually know that they are (ie most netcdf dimensions). So we need to track that information separately from the vector.

Any solution would probably have to allow tracking the order of regular vectors as well.

**Comment by ivirshup** [comment]
> Any solution would probably have to allow tracking the order of regular vectors as well.

I'm not sure it does. This can't be type stable since whether `A[::Vector]` is ordered is only known once you look at the values. But you could say `(A::Ordered[::Ordered])::Ordered` `(A::Ordered[B::Vector])::Unordered`.

About `At`, for containers which are known to be ordered, `findfirst`  and `searchsortedfirst` should probably be equivalent. I think this is how it works in AcceleratedArrays and AxisIndices.

**Comment by rafaqz** [comment]
> I'm not sure it does.

`Near` needs it to be. `searchsortedfirst` is ordered, dims can hold a vector index, and Near uses `searchsortedfirst` on vectors.

But we often know the order and set the order trait manually at construction. For eg. Netcdf we have an index vector, a known standard dim order and a standard array order. And we construct the dim with those traits.

This use case is completely type stable - and the actual core reason for having an order field at all in the first place.

How else could we do this?

**Comment by ivirshup** [comment]
Touching back on this, I was thinking that the ordering could be deferred to the type of the dimension. I.e. is could be something like a `SortedVector`: https://github.com/JuliaCollections/DataStructures.jl/pull/290

For `Near`, is this strictly needed? It's just needed for a simple calculation, but I believe `xarray` does nearest neighbor look ups. Also, this case becomes more complicated for `Coords`.

A wrapper type would be great, but a trait is more likely. I believe a wrapper type like this has been suggested a few times as a language feature, but I'm not sure what's up with that. `(A::Ordered[::Ordered])::Ordered` would be for a wrapper type.

Since a number of packages have ordered collections, it's probably easier to just make it a trait at this point. To me, ordering makes more sense as a feature of the dimension, rather than the grid. Some dimensions can be ordered, while others aren't.

**Comment by rafaqz** [comment]
> For Near, is this strictly needed

Otherwise you have to look at every element n the vector. `searchsortedfirst` is much faster than that (it's a binary search or something similar).

>To me, ordering makes more sense as a feature of the dimension, rather than the grid. 

Yeah all that stuff is on the grid currently. It's not necessarily the best solution in the end. Maybe we can move it at some stage.

**Comment by rafaqz** [comment]
I've worked on this in:
https://github.com/rafaqz/DimensionalData.jl/pull/115/files

Some take-aways:
- `Categorical` index is `Unordered()` by default now, and wont try to find an order. You can manually set `Ordered()` if you want to.
- `Sampled` index checks order and `issorted`. I used a python style `try catch` block to just
catch the error is `isless` isn't available. It's faster than using `methodswith` and will rarely happen
anyway.

Let me know if the tests make sense to you. A lot of the type names have been simplified too.
