### ISSUE TITLE
Tests for type stability

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#99]
It would be good to make sure operations that are supposed to be type stable actually are. I've managed to think I was making a few clever changes, only to later find out they caused type instability. I'm thinking this could implemented in the tests with a macro like:

<details>
<summary> basically `Test.@inferred` </summary>

```julia
using Test

macro test_type_stable(expr)
    if expr.head == :ref
        expr = :(getindex($(expr.args...)))
    end
    if expr.head != :call
        throw(ErrorException("@test_type_stable expected a call, got $(expr)"))
    end
    func = popfirst!(expr.args)
    arg_types = map(x->:(typeof($x)), expr.args)
    quote
        ts = Base.return_types($func, Tuple{$(arg_types...)})
        @test length(ts) == 1
        @test isconcretetype(ts[1])
    end
end

@test_type_stable da[1, :]
@test_type_stable da[X(At(1:4))]
```

</details>

## Things that should have tests for stability

- [ ] Indexing
    - [ ] By position `da[i, j, ...]`
    - [ ] By dimension `da[X(i), Y(j), ...]`
    - [ ] Setting values by position or dimension `da[i, j, ...] = ...`
    - [ ] Views by position or dimension
    - [ ] Assigning to views
- [ ] Shape changes
    - [ ] `dropdim`
    - [ ] Reshape (likely drops dimension data)
    - [ ] `permutedims` for all argument types
- [ ] Broadcasting
    - [ ] Broadcast assignment
    - [ ] Broadcasting between types of containers
- [ ] Methods
    - [ ] reductions (e.g. `reduce`, `mean`, ...)
    - [ ] iterators (e.g. `eachslice`, `mapslices`, ...)
- [ ] Constructors (currently not type stable, #93 )
    - [ ] `DimensionalArray`
    - [ ] Grids

**Comment by rafaqz** [comment]
`@inferred` ?

**Comment by ivirshup** [comment]
That'd work too! Main thing would be using it though.

**Comment by ivirshup** [comment]
I've started a checklist of things that should get tests for stability at the top of the issue. Feel free to add to it.

Is there a way to test if an operation (say, `DimensionalData._sortdims((X(), Y()), (Y(),))`) is computed at compile time?

**Comment by rafaqz** [comment]
>Is there a way to test if an operation (say, DimensionalData._sortdims((X(), Y()), (Y(),))) is computed at compile time?

I'm not sure that's possible. You can benchmark and test allocations...

**Comment by ivirshup** [comment]
For testing if it's computed at compile time: `@code_llvm` or `@code_native` are possible solutions.

Some initial issues:

* `view` with >3 `At` indexers with scalar values (e.g. `At(1)`) are type unstable when they aren't all ints.
* `At` seems rough on inference. The more arguments the worse.
* For this case: `DimensionalArray(randn(2, 2, 2, 2), (X([1, 2]), Y(2:-1:1), Z(100:50:150), Dim{:W}([-2, -100])))`, there are a lot of inference errors from dimensional indexing when `Dim{:W}` and `Z` are both used. Not if other combinations are used.
* When inference is failing, the result type tends to be `Union{typeof(data(result)), typeof(result)}`

**Comment by rafaqz** [comment]
Interesting. It sounds like the compiler giving up on inlining recursive methods. Maybe moving to recursion instead of `@generated` wasn't such a good idea. But maybe we have some `@inline` missing somewhere.

https://github.com/JuliaDebug/Cthulhu.jl might help.

Not sure about the unions. But that is weird that `Dim{:W}` is an issue.

**Comment by ivirshup** [comment]
> It sounds like the compiler giving up on inlining recursive methods.

I'm thinking this is currently mostly around `dims2indices` and `view`, since those bring up a lot of errors. I'll open up a WIP PR with some tests if you're interested in seeing what fails. It's a little over the top at the moment, but it's providing useful results.

----------------------------------

Oh my (dark) god, Cthulu looks like it'll save me so much pain. Thanks for pointing that out!

**Comment by ivirshup** [comment]
> Not sure about the unions. But that is weird that Dim{:W} is an issue.

Update, I think it doesn't matter that it was `Dim{:W}`, I think it matters that `Z` and `Dim{:W}` were the third and fourth dimensions. Running the dimensional indexing tests with the arrays: `DimensionalArray(randn(10, 10, 10, 10), (X, Y, Z, Ti))` and `DimensionalArray(randn(10, 10, 10, 10), (Dim{:W}, Dim{:X}, Dim{:Y}, Dim{:Z}))` error the same amount of times. This is with `@inline` on.

I'm wondering if `_sortdims` could be defined non-recursively, but marked with `@pure`? It might better force specialization?

**Comment by ivirshup** [comment]
Potentially relevant to this, why are: `X`, `Y`, `Z`, and `Ti` different from dimensions defined like `Dim{:X}`?

**Comment by rafaqz** [comment]
Pure is not cool... so many weird bugs you can introduce.

What do you mean by why are they different? why do they compile differently or why they exist?

**Comment by ivirshup** [comment]
Why define X as a type with a macro and not as `Dim{:X}`?

You could still define names like `shortname(::Dim{:X}) = "X"`, and get plotting behaviour through traits (`plotdim(::Dim{:X}) = XAxis`). It seems like this could simplify the package a bit.

----------------------------------

What was you experience with `@pure`? All I've gotten so far is much better inference.

**Comment by rafaqz** [comment]
pure is more like hyperpure. Its probably stricter than than you think. But could be ok here idk.

The double up is mostly for nicer syntax. I hate the `Dim` syntax, its basically AxisArrays again. I want to just use `X`.  You also lose the ability to inherit dim behaviours.

**Comment by ivirshup** [comment]
I'm starting to think this is a good use case for `@generated`. Any objection to moving back to that, given the inference failures?

-------------------------------

`da[Dim{:A}([1,2,3])]` is bad, but I've just been doing:

```julia
A = Dim{:A}  # as opposed to: @dim A
da[A([1, 2, 3])]
```

Which is pretty similar to using `@dim`, but has more normal scoping rules than defining a struct. It also allows definitions like:

```julia
_dimsmatch(dim::Dim{T}, match::Type{<:Dim{T}}) where T = true
```

I'll think about your point on inheritance.

**Comment by rafaqz** [comment]
We should aim for the minimum number og generated funcions for type stabilty. I only timed with three dims so I never saw the performamce loss.

Mostly people wont use `@dim` (I never do). The predefined dims will cover a lot of cases. 

In my experience types are preferable and open up more future possibilities. Symbols give you nothing.
